#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Header / DTS / mount-table emitters from the resolved model.

Pure renderers off the parsed BoardProject + the resolved carve-outs / storage
partitions: the IPC contract header (ipc-contract-h), the DTS reserved-memory
overlay (dts-reservations), the DTS fixed-partitions overlay (dts-partitions),
and the static C mount table (storage-mounts-c). Each is a leaf emit -- it calls
only the carve-out / partition resolvers, never the loader/validator. Extracted
as the #285 headers emit seam.
"""

from __future__ import annotations

from .carveout import resolve_carve_outs
from .models import BoardProject, ResolvedPartition
from .partition import resolve_storage_partitions


def emit_ipc_contract_h(project: BoardProject) -> str:
    """Generate alp_system_ipc.h per spec §6.3."""
    carve_outs = resolve_carve_outs(project)

    lines: list[str] = [
        "/*",
        " * Auto-generated by scripts/alp_orchestrate.py -- do not edit.",
        " * Regenerate after changes to board.yaml `ipc:` or the SoM's",
        " * memory_map / mailbox blocks.",
        " */",
        "",
        "#ifndef ALP_SYSTEM_IPC_H",
        "#define ALP_SYSTEM_IPC_H",
        "",
        f'#define ALP_IPC_SKU "{project.sku}"',
        "",
    ]
    if not carve_outs:
        lines += [
            "/* No ipc[] entries declared in board.yaml; nothing to emit. */",
            "",
            "#endif /* ALP_SYSTEM_IPC_H */",
            "",
        ]
        return "\n".join(lines)

    for c in carve_outs:
        upper = c.name.upper()
        lines.append(f"/* {c.kind} channel '{c.name}' -- endpoints "
                     f"{', '.join(c.endpoints)} */")
        if c.status == "blocked":
            # Blocked entries still need the SRC_EPT / DST_EPT / MBOX_CH /
            # ADDR / SIZE macros so consumer source compiles: the
            # canonical pattern (see examples/rpmsg-*/m*/src/main.c) is a
            # static struct initialiser that references every field at
            # compile time.  Omitting the macros made every rpmsg
            # consumer fail with `<macro> undeclared` long before the
            # NOSUPPORT runtime check could even fire.  Emit safe-zero
            # stubs + a #warning so the build is green and the gap is
            # surfaced via the alp_rpc_open() ALP_ERR_NOSUPPORT path
            # the backend already returns when it sees a zero
            # mailbox_channel or empty mailbox controller.
            lines.append(f"/* BLOCKED: {c.reason or 'unknown reason'} */")
            # Surface the gap as a structured comment block rather than
            # a `#warning` (the slice builds under -Werror=cpp and an
            # actual warning would trip it).  The same reason text is
            # also written into the build manifest by the orchestrator's
            # fan-out step so reviewers see it.
            lines.append(f"/* IPC channel '{c.name}' is blocked; "
                         "fix the SoM metadata before depending on this "
                         "channel at runtime. */")
            lines.append(f'#define ALP_IPC_{upper}_NAME       "{c.name}"')
            lines.append(f"#define ALP_IPC_{upper}_ADDR       0x0u  /* stub: blocked */")
            lines.append(f"#define ALP_IPC_{upper}_SIZE       0x0u  /* stub: blocked */")
            lines.append(f"#define ALP_IPC_{upper}_SRC_EPT    0x0u  /* stub: blocked */")
            lines.append(f"#define ALP_IPC_{upper}_DST_EPT    0x0u  /* stub: blocked */")
            lines.append(f"#define ALP_IPC_{upper}_MBOX_CH    0u    /* stub: blocked */")
            lines.append("")
            continue
        lines.append(f'#define ALP_IPC_{upper}_NAME       "{c.name}"')
        lines.append(f'#define ALP_IPC_{upper}_ADDR       0x{c.base:08x}u')
        lines.append(f'#define ALP_IPC_{upper}_SIZE       0x{c.size:08x}u')
        lines.append(f'#define ALP_IPC_{upper}_SRC_EPT    0x{c.src_ept:08x}u')
        lines.append(f'#define ALP_IPC_{upper}_DST_EPT    0x{c.dst_ept:08x}u')
        lines.append(f'#define ALP_IPC_{upper}_MBOX_CH    {c.mailbox_channel}u')
        lines.append("")

    lines.append("#endif /* ALP_SYSTEM_IPC_H */")
    lines.append("")
    return "\n".join(lines)


def emit_dts_reservations(project: BoardProject) -> str:
    """Generate dts-reservations.dtsi per spec §6.2."""
    carve_outs = resolve_carve_outs(project)
    lines: list[str] = [
        "/*",
        " * Auto-generated by scripts/alp_orchestrate.py -- do not edit.",
        " * Regenerate after changes to board.yaml `ipc:` or the SoM's",
        " * memory_map block.  #include this file from your kernel /",
        " * Zephyr DT.",
        " */",
        "",
        "/ {",
        "    reserved-memory {",
        "        #address-cells = <2>;",
        "        #size-cells = <2>;",
        "",
    ]
    if not carve_outs:
        lines.append("        /* No ipc[] carve-outs declared. */")
    else:
        for c in carve_outs:
            if c.status == "blocked":
                # Blocked carve-outs land as a comment so reviewers see
                # the gap; the slice build trips elsewhere (the C
                # header carries an #error directive).
                lines.append(f"        /* BLOCKED: {c.name} -- "
                             f"{c.reason or 'unknown reason'} */")
                lines.append("")
                continue
            # Split base / size into two 32-bit halves for the
            # #address-cells = <2>; #size-cells = <2>; addressing.
            base_hi = (c.base >> 32) & 0xFFFFFFFF
            base_lo = c.base & 0xFFFFFFFF
            size_hi = (c.size >> 32) & 0xFFFFFFFF
            size_lo = c.size & 0xFFFFFFFF
            lines.append(
                f"        {c.name}: {c.name}@{c.base:x} {{")
            lines.append(
                '            compatible = "shared-dma-pool";')
            lines.append(
                f"            reg = <0x{base_hi:x} 0x{base_lo:08x} "
                f"0x{size_hi:x} 0x{size_lo:08x}>;")
            lines.append("            no-map;")
            lines.append(f'            label = "{c.name}";')
            lines.append("        };")
            lines.append("")

    lines.append("    };")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def emit_dts_partitions(project: BoardProject) -> str:
    """Generate dts-partitions.dtsi from board.yaml `storage:`.

    The overlay decorates each referenced flash device with a
    `partitions { ... }` child node carrying every resolved
    partition for that device.  Zephyr's `fixed-partitions` binding
    consumes the result; downstream Kconfig (CONFIG_FILE_SYSTEM_LITTLEFS
    etc., emitted by `_slice_alp_conf()`) wires the filesystem driver.

    Blocked partitions appear as bare comments so reviewers see the
    gap; the slice build trips elsewhere (the per-fs Kconfig will not
    have a backing partition and Zephyr's link-time fs-table assembly
    surfaces the error).
    """
    partitions = resolve_storage_partitions(project)
    lines: list[str] = [
        "/*",
        " * Auto-generated by scripts/alp_orchestrate.py -- do not edit.",
        " * Regenerate after changes to board.yaml `storage:` or the SoM's",
        " * memory_map / on_module.ospi_memories blocks.  #include this file",
        " * from your Zephyr DT.",
        " */",
        "",
    ]
    if not partitions:
        lines += [
            "/* No `storage:` entries declared in board.yaml; nothing to emit. */",
            "",
        ]
        return "\n".join(lines)

    # Group resolved partitions by dt_label; blocked entries get a
    # standalone comment block so reviewers see the gap.
    by_label: dict[str, list[ResolvedPartition]] = {}
    blocked: list[ResolvedPartition] = []
    for p in partitions:
        if p.status == "blocked":
            blocked.append(p)
            continue
        by_label.setdefault(p.dt_label, []).append(p)

    for label in sorted(by_label.keys()):
        lines.append(f"&{label} {{")
        lines.append("    partitions {")
        lines.append('        compatible = "fixed-partitions";')
        lines.append("        #address-cells = <1>;")
        lines.append("        #size-cells = <1>;")
        lines.append("")
        # Sort by base offset for human readability + DT-binding
        # convention (low-address first).
        for p in sorted(by_label[label], key=lambda x: x.base_kib):
            base_bytes = p.base_kib * 1024
            size_bytes = p.size_kib * 1024
            lines.append(
                f"        {p.name}_partition: partition@{base_bytes:x} {{")
            lines.append(f'            label = "{p.name}";')
            lines.append(
                f"            reg = <0x{base_bytes:x} 0x{size_bytes:x}>;")
            lines.append("        };")
            lines.append("")
        lines.append("    };")
        lines.append("};")
        lines.append("")

    if blocked:
        lines.append(
            "/* Blocked storage entries -- see system-manifest.yaml for details. */")
        for p in blocked:
            lines.append(f"/* BLOCKED: {p.name} -- "
                         f"{p.reason or 'unknown reason'} */")
        lines.append("")

    return "\n".join(lines)


def emit_storage_mounts_c(project: BoardProject) -> str:
    """Generate storage_mount_table.c -- a static fs_mount_t[] array.

    Optional companion to emit_dts_partitions.  Apps that want
    deterministic boot-time mounting include this file and call
    `alp_storage_mount_all()` (or iterate the table manually).
    Partitions with no `mount:` declared are omitted from the table.
    """
    partitions = resolve_storage_partitions(project)
    mountable = [p for p in partitions
                 if p.status == "ok" and p.mount and p.fs != "raw"]

    lines: list[str] = [
        "/*",
        " * Auto-generated by scripts/alp_orchestrate.py -- do not edit.",
        " * Regenerate after changes to board.yaml `storage:`.",
        " */",
        "/* clang-format off */",
        "",
        "#include <zephyr/fs/fs.h>",
        "#include <zephyr/storage/flash_map.h>",
        "",
    ]
    if not mountable:
        lines += [
            "/* No mountable storage[] entries declared; emitting empty table. */",
            "",
            "const struct fs_mount_t *alp_storage_mounts[] = { 0 };",
            "const size_t alp_storage_mount_count = 0;",
            "/* clang-format on */",
            "",
        ]
        return "\n".join(lines)

    # Per-fs includes + per-partition fs_<name>_data + fs_mount_t.
    fs_seen: set[str] = set()
    for p in mountable:
        if p.fs in fs_seen:
            continue
        fs_seen.add(p.fs)
        if p.fs == "littlefs":
            lines.append("#include <zephyr/fs/littlefs.h>")
        elif p.fs == "fat":
            lines.append("#include <ff.h>")
        elif p.fs == "ext4":
            lines.append("#include <zephyr/fs/ext2.h>")
    lines.append("")

    for p in mountable:
        upper = p.name.upper()
        if p.fs == "littlefs":
            lines.append(f"FS_LITTLEFS_DECLARE_DEFAULT_CONFIG(alp_lfs_{p.name});")
            lines.append(f"static struct fs_mount_t alp_mnt_{p.name} = {{")
            lines.append("    .type = FS_LITTLEFS,")
            lines.append(f"    .fs_data = &alp_lfs_{p.name},")
            lines.append(f"    .storage_dev = (void *)FIXED_PARTITION_ID({p.name}_partition),")
            lines.append(f'    .mnt_point = "{p.mount}",')
            lines.append("};")
        elif p.fs == "fat":
            lines.append(f"static FATFS alp_fat_{p.name};")
            lines.append(f"static struct fs_mount_t alp_mnt_{p.name} = {{")
            lines.append("    .type = FS_FATFS,")
            lines.append(f"    .fs_data = &alp_fat_{p.name},")
            lines.append(f"    .storage_dev = (void *)FIXED_PARTITION_ID({p.name}_partition),")
            lines.append(f'    .mnt_point = "{p.mount}",')
            lines.append("};")
        elif p.fs == "ext4":
            lines.append(f"static struct fs_mount_t alp_mnt_{p.name} = {{")
            lines.append("    .type = FS_EXT2,")
            lines.append(f"    .storage_dev = (void *)FIXED_PARTITION_ID({p.name}_partition),")
            lines.append(f'    .mnt_point = "{p.mount}",')
            lines.append("};")
        lines.append("")
        # Silence -Wunused on the per-partition mount when the app
        # iterates only via alp_storage_mounts[]; the explicit symbol
        # lets test fixtures reach a specific mount by name.
        _ = upper

    lines.append("const struct fs_mount_t *alp_storage_mounts[] = {")
    for p in mountable:
        lines.append(f"    &alp_mnt_{p.name},")
    lines.append("};")
    lines.append("const size_t alp_storage_mount_count = "
                 f"{len(mountable)};")
    lines.append("/* clang-format on */")
    lines.append("")
    return "\n".join(lines)
