#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Per-slice Kconfig (alp.conf) emitter.

`_slice_alp_conf` renders a Zephyr slice's Kconfig fragment off the parsed model
+ the resolved capabilities / chip-driver / library / peripheral enables;
`_emit_extra_library_profile` renders an extra `libraries:` profile fragment.
Extracted as the #285 kconfig emit seam. The slug / peripheral-Kconfig tables
come from the slugs.py leaf; the `_CHIP_SUBSYSTEMS` table is lazy-imported from
alp_project inside the function (the existing alp_project<->alp_orchestrate
cycle-break), with the same in-body sys.path setup. Per-core `libraries:`
Kconfig is read from each library's manifest via `_per_core_library_kconfig`.

`_slice_alp_conf` itself is a thin composer over a set of `_emit_*` section
helpers (console / SoM capability / chip driver / subsystem / library /
inference / memory / power / storage / OTA / diagnostics), each returning
that section's `list[str]` fragment. Split out mechanically as the #673
Phase-1 kconfig split -- behavior-preserving, byte-identical emit output;
see `check_emit_snapshots.py`.

This module is a pure string templater: it never runs kconfiglib/west, so
every emitted `CONFIG_*` line must be provable correct from this module's own
YAML/JSON inputs + its own `zephyr/kconfigs/*.kconfig` tree -- it cannot ask
the real Kconfig solver whether a symbol's dependency chain resolves.
Consequently the emitted alp.conf's Kconfig symbol set is coupled to the
alp-sdk module version that generated it, the same way `west.yml` deliberately
pins one Zephyr/module release at a time (docs/zephyr-version-policy.md); an
alp.conf generated by one alp-sdk version is not a promised-compatible input
to a Zephyr tree built against another. Detecting that cross-version skew
cleanly (rather than a Kconfig "assign to undefined symbol" abort) is #855's
job, not this module's -- this module only owns intra-version dependency
gating (see #874).
"""

from __future__ import annotations

import json
from typing import Any, Optional

import yaml

from alp_project import (
    resolve_capabilities,
    silicon_to_kconfig,
    som_unpopulated_capabilities,
)

from . import libraries as _library_layer
from .models import BoardProject, Slice
from .paths import METADATA_ROOT, REPO
from .partition import resolve_storage_partitions
from .slugs import (
    _PERIPHERAL_KCONFIG,
    _board_define_slug,
    _slugs_from_helper_firmware,
    _slugs_from_on_module,
    _som_define_slug,
)


def _emit_extra_library_profile(
    name: str,
    profile_rel: str,
    project: "BoardProject",
) -> list[str]:
    """Walk an extra_libraries `profile:` file and emit the per-class
    first-match Kconfig lines for the active SoM.

    Mirrors the curated-library `integration.zephyr.hw_backends` matcher
    (folded into each `metadata/libraries/<lib>.yaml` manifest): each
    accelerator class declares a `priority:` list whose entries carry
    `silicon:` / `soc_family:` / `requires_cap:` matchers plus a
    `kconfig:` directive.  Entries marked `status: planned` or
    `status: stub` are metadata only and are not emitted as active
    build claims.  First matching implemented entry per class wins; an
    `sw_fallback:` block with `kconfig:` is always emitted at the end
    so the build has a SW floor when no HW backend matches.

    Returns the list of emitted lines (each line is a complete
    `CONFIG_*=y` or `# ...` comment); empty list when the profile
    parses but nothing matches and there's no sw_fallback.

    Failures (malformed YAML, missing keys) emit a single `#`-prefixed
    diagnostic comment so the customer sees the failure in the slice's
    alp.conf rather than getting silent drop-out.
    """
    profile_path = (REPO / profile_rel).resolve()
    try:
        doc = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as e:
        return [f"# extra_libraries[{name}] profile parse failed: {e}"]
    if not isinstance(doc, dict):
        return [f"# extra_libraries[{name}] profile is not a mapping"]

    # Match keys come from the active SoM.  Mirror
    # alp_project._SOC_FAMILY_TOKEN so extra_libraries entries can
    # share existing curated-profile match keys when desired.
    silicon_ref = project.som_preset.get("silicon") or ""
    family = (project.som_preset.get("family") or "").lower()
    soc_family_token: Optional[str] = None
    if family.startswith("alif-ensemble"):
        soc_family_token = "alif_ensemble"
    elif family.startswith("renesas-rzv2n"):
        soc_family_token = "renesas_rzv2n"
    elif family.startswith("nxp-imx9"):
        soc_family_token = "nxp_imx9"

    # resolve_capabilities merges SoC-JSON defaults + SoM overrides.
    capabilities = resolve_capabilities(project.som_preset, METADATA_ROOT)

    def _cap_truthy(cap_name: str) -> bool:
        v = capabilities.get(cap_name)
        if v is None:
            return False
        if isinstance(v, bool):
            return v
        if isinstance(v, int):
            return v > 0
        s = str(v).lower()
        if s in ("true", "yes"):
            return True
        if s in ("false", "no", "null", "none", "0", ""):
            return False
        try:
            return int(s) > 0
        except ValueError:
            return False

    def _entry_matches(e: dict[str, Any]) -> bool:
        status = str(e.get("status", "implemented")).strip().lower()
        if status in {"planned", "stub"}:
            return False
        sili = e.get("silicon")
        sf = e.get("soc_family")
        cap = e.get("requires_cap")
        if sili is not None and sili != silicon_ref:
            return False
        if sf is not None and sf != soc_family_token:
            return False
        if cap is not None and not _cap_truthy(str(cap)):
            return False
        return True

    out: list[str] = []
    accelerators = doc.get("accelerators") or []
    if isinstance(accelerators, list):
        for cls in accelerators:
            if not isinstance(cls, dict):
                continue
            cls_name = cls.get("class") or "<unknown>"
            for p in (cls.get("priority") or []):
                if not isinstance(p, dict):
                    continue
                if not _entry_matches(p):
                    continue
                kc = p.get("kconfig")
                if isinstance(kc, str) and kc:
                    out.append(f"{kc}  # {name} / {cls_name}")
                break

    sw = doc.get("sw_fallback")
    if isinstance(sw, dict):
        kc = sw.get("kconfig")
        if isinstance(kc, str) and kc:
            out.append(f"{kc}  # {name} / sw_fallback")

    return out


# --------------------------------------------------------------------
# Console backend auto-selection (issue: generic console).
#
# The Alp SDK is a generic, multi-OS SoM layer: the same example can be
# built for a Zephyr core (Cortex-M) or a Linux core (Cortex-A / Yocto),
# and the console backend that "printf lands on" differs per OS.  Rather
# than force every app author to hand-pick console Kconfig (the old AEN
# bench examples hard-coded a RAM console, which then fought the board's
# real UART console), the generator selects it automatically from the
# slice's `os:` and lets the SoM manufacturer / customer override via a
# single `diagnostics.console:` knob in board.yaml.
#
#   auto  (default) -> os: zephyr        => alp  (UART console)
#                      os: yocto/ubuntu  => linux (stdio/tty console)
#                      other             => none
#   alp | uart      -> Zephyr UART console (the module's console UART,
#                       e.g. E1M edge UART0; the board layer owns the
#                       `zephyr,console` DT chosen + pinmux).
#   ram             -> Zephyr RAM console (bench flow: read the buffer
#                       over SWD when no serial line is available).
#   linux           -> Linux console (nothing to emit on the Zephyr side;
#                       meaningful only on a yocto slice).
#   none | off      -> emit nothing; inherit whatever the board provides.
# --------------------------------------------------------------------
_CONSOLE_ALIASES = {
    "alp": "uart",
    "uart": "uart",
    "serial": "uart",
    "ram": "ram",
    "swd": "ram",
    "linux": "linux",
    "stdio": "linux",
    "none": "none",
    "off": "none",
}


def _resolve_console(value: Optional[str], os_: str,
                     hw_console: bool = True) -> str:
    """Resolve the effective console backend for a slice.

    ``value`` is the raw ``diagnostics.console:`` knob (or ``None`` /
    ``"auto"`` for the OS-derived default); ``os_`` is the slice OS.
    ``hw_console`` is the SoM-topology fact (``topology.<id>.hw_console``):
    a headless core (``False``) has no hardware UART console, so the
    AUTO-resolved Zephyr default must be ``"none"`` (inherit the board
    default) instead of ``"uart"`` -- emitting ``CONFIG_UART_CONSOLE=y``
    on a core whose board has no serial driver is an "assigned y but got n"
    Kconfig error, fatal to the Zephyr build (issue #717).  An explicit
    ``diagnostics.console:`` still wins for a headless core (the caller may
    upgrade a headless AUTO to ``"ram"`` via ``diagnostics.sim_console``,
    #686).  Returns one of ``"uart"``, ``"ram"``, ``"linux"``, ``"none"``.
    """
    v = (value or "auto").strip().lower()
    if v == "auto":
        if os_ == "zephyr":
            return "uart" if hw_console else "none"
        if os_ in ("yocto", "ubuntu"):
            return "linux"
        return "none"
    return _CONSOLE_ALIASES.get(v, "none")


def _emit_zephyr_console(console: str, sim_console: bool = False) -> list[str]:
    """Kconfig lines for a Zephyr slice's resolved console backend.

    ``sim_console`` distinguishes a RAM console selected explicitly via
    ``diagnostics.console: ram`` (bench SWD flow) from one auto-selected
    for a headless core by ``diagnostics.sim_console: true`` (studio sim
    streams the ring over ``uart_socket``); the emitted Kconfig is
    identical, only the teaching comment differs.
    """
    if console == "uart":
        return [
            "# Console: Alp UART console (auto-selected for os: zephyr).",
            "# printf/LOG land on the module's console UART (the board layer",
            "# owns the `zephyr,console` DT chosen + pinmux -- e.g. E1M edge",
            "# UART0).  Override in board.yaml with `diagnostics.console: ram`",
            "# (SWD bench flow) or `none` (inherit the board default).",
            "CONFIG_SERIAL=y",
            "CONFIG_CONSOLE=y",
            "CONFIG_UART_CONSOLE=y",
            "CONFIG_UART_INTERRUPT_DRIVEN=y",
            "",
        ]
    if console == "ram":
        header = (
            [
                "# Console: RAM console (board.yaml `diagnostics.sim_console: "
                "true`).",
                "# This core has no hardware UART console -- the studio",
                "# simulator streams `ram_console_buf` over its `uart_socket`.",
            ]
            if sim_console
            else [
                "# Console: RAM console (board.yaml `diagnostics.console: "
                "ram`).",
                "# No serial line on this bench -- read `ram_console_buf` "
                "over SWD.",
            ]
        )
        return header + [
            "# LOG is routed to printk so the RAM backend still captures it.",
            "CONFIG_CONSOLE=y",
            "CONFIG_RAM_CONSOLE=y",
            "CONFIG_RAM_CONSOLE_BUFFER_SIZE=2048",
            "CONFIG_UART_CONSOLE=n",
            "",
        ]
    # "linux" on a Zephyr slice is meaningless, and "none" means inherit
    # the board default -- emit nothing in both cases.
    return []


_LINUX_WIRELESS_PROVIDER_PREFIXES = ("murata_", "cyw")


def _wireless_provider(project: BoardProject) -> Optional[str]:
    """Return the SoM's on-module Wi-Fi/BLE provider slug, if known."""
    om = project.som_preset.get("on_module") or {}
    provider = om.get("wifi_ble")
    if not isinstance(provider, str):
        return None
    provider = provider.strip()
    if not provider or provider == "TBD":
        return None
    return provider


def _is_linux_wireless_provider(provider: Optional[str]) -> bool:
    """True when Wi-Fi/BLE data paths are owned by the Linux BSP stack."""
    if provider is None:
        return False
    return provider.startswith(_LINUX_WIRELESS_PROVIDER_PREFIXES)


def _zephyr_iot_kconfig(
    project: BoardProject,
    slice_: Slice,
    resolved_chip_state: dict[str, bool],
) -> list[str]:
    """Kconfig lines for ``cores.<id>.iot`` on a Zephyr slice.

    ``resolved_chip_state`` is the same som -> board-populated -> project-chips
    resolved on/off map ``_emit_chips`` prints from (see
    ``_resolve_chip_states``) -- the CC3501E bridge backend
    (``ALP_SDK_WIFI_CC3501E`` / ``ALP_SDK_BLE_CC3501E``) ``depends on
    ALP_SDK_CHIP_CC3501E``, so a board variant that turns the chip off via
    ``populated: { cc3501e: false }`` must not also get a Wi-Fi/BLE
    ``=y`` line that silently resolves to n (issue #874).
    """
    iot = slice_.iot or {}
    if not any(iot.get(k) for k in ("wifi", "mqtt", "tls", "ble")):
        return []

    provider = _wireless_provider(project)
    lines: list[str] = [
        f"# IoT features declared on core `{slice_.core_id}` "
        "(board.yaml `cores.*.iot`)",
    ]
    if provider:
        lines.append(
            f"# Wireless provider resolved from `{project.sku}` "
            f"on_module.wifi_ble: {provider}.")
    else:
        lines.append("# Wireless provider is TBD/absent; using generic Zephyr stack gates.")

    emitted: set[str] = set()

    def add(line: str) -> None:
        if line.startswith("CONFIG_"):
            if line in emitted:
                return
            emitted.add(line)
        lines.append(line)

    def add_network_base() -> None:
        add("CONFIG_NETWORKING=y")
        add("CONFIG_NET_IPV4=y")
        add("CONFIG_NET_SOCKETS=y")

    linux_owned = _is_linux_wireless_provider(provider)

    if iot.get("wifi"):
        if provider == "cc3501e":
            if resolved_chip_state.get("cc3501e"):
                add("# Wi-Fi: AEN CC3501E bridge backend, not Zephyr wifi_mgmt.")
                add("CONFIG_ALP_SDK_WIFI_CC3501E=y")
            else:
                add("# Wi-Fi: SoM wireless provider is CC3501E, but this board")
                add("# does not populate the chip (board.yaml `populated.cc3501e: "
                    "false`);")
                add("# no Wi-Fi backend is emitted for this slice.")
        elif linux_owned:
            add("# Wi-Fi: provider data path is Linux/BSP-owned on this SoM;")
            add("# no Zephyr wifi_mgmt backend is emitted for this slice.")
        else:
            add("# Wi-Fi: generic Zephyr wifi_mgmt station path.")
            add_network_base()
            add("CONFIG_WIFI=y")
            add("CONFIG_NET_MGMT=y")
            add("CONFIG_NET_MGMT_EVENT=y")
            add("CONFIG_NET_L2_WIFI_MGMT=y")
            add("CONFIG_ALP_SDK_IOT_WIFI=y")

    if iot.get("mqtt"):
        add("# MQTT: Zephyr mqtt_client over the active socket provider.")
        add_network_base()
        add("CONFIG_NET_TCP=y")
        add("CONFIG_MQTT_LIB=y")
        add("CONFIG_ALP_SDK_IOT_MQTT=y")

    if iot.get("tls"):
        add("# TLS: credential store + TLS-capable protocol clients.")
        # TLS_CREDENTIALS needs the networking base even when neither
        # `wifi:` nor `mqtt:` is also set on this slice -- omitting it left
        # CONFIG_TLS_CREDENTIALS=y silently resolving to n (unmet
        # NETWORKING/NET_SOCKETS deps), issue #874.  add_network_base()
        # dedupes against the wifi/mqtt branches above.
        add_network_base()
        add("CONFIG_TLS_CREDENTIALS=y")
        if iot.get("mqtt"):
            add("CONFIG_MQTT_LIB_TLS=y")

    if iot.get("ble"):
        if provider == "cc3501e":
            if resolved_chip_state.get("cc3501e"):
                add("# BLE: AEN CC3501E bridge backend, not Zephyr HCI.")
                add("CONFIG_ALP_SDK_BLE_CC3501E=y")
            else:
                add("# BLE: SoM wireless provider is CC3501E, but this board")
                add("# does not populate the chip (board.yaml `populated.cc3501e: "
                    "false`);")
                add("# no BLE backend is emitted for this slice.")
        elif linux_owned:
            add("# BLE: provider data path is Linux/BSP-owned on this SoM;")
            add("# no Zephyr BT-host backend is emitted for this slice.")
        else:
            add("# BLE: generic Zephyr BT host path.")
            add("CONFIG_BT=y")
            add("CONFIG_BT_PERIPHERAL=y")
            add("CONFIG_BT_CENTRAL=y")
            add("CONFIG_ALP_SDK_BLE=y")

    lines.append("")
    return lines


def _yocto_iot_lines(project: BoardProject, slice_: Slice) -> list[str]:
    """local.conf lines for ``cores.<id>.iot`` on a Yocto slice."""
    iot = slice_.iot or {}
    if not any(iot.get(k) for k in ("wifi", "mqtt", "tls", "ble")):
        return []

    provider = _wireless_provider(project)
    lines: list[str] = [
        "",
        f"# IoT features declared on core `{slice_.core_id}` "
        "(board.yaml `cores.*.iot`)",
    ]
    if provider:
        lines.append(
            f"# Wireless provider resolved from `{project.sku}` "
            f"on_module.wifi_ble: {provider}.")
    else:
        lines.append("# Wireless provider is TBD/absent; emit generic Linux userland.")

    image_pkgs: list[str] = []
    packageconfig: list[str] = []

    def add_unique(seq: list[str], value: str) -> None:
        if value not in seq:
            seq.append(value)

    linux_owned = _is_linux_wireless_provider(provider)

    if iot.get("wifi"):
        if provider == "cc3501e":
            lines.append("# Wi-Fi: CC3501E is controlled by the Zephyr/companion path.")
        else:
            if linux_owned:
                lines.append(
                    "# Wi-Fi: Linux owns this provider's SDIO/firmware path; "
                    "BSP/machine recipes supply kernel/firmware packages.")
            add_unique(image_pkgs, "wpa-supplicant")
            add_unique(image_pkgs, "iw")
            add_unique(image_pkgs, "wireless-regdb")

    if iot.get("ble"):
        if provider == "cc3501e":
            lines.append("# BLE: CC3501E is controlled by the Zephyr/companion path.")
        else:
            if linux_owned:
                lines.append(
                    "# BLE: Linux owns this provider's HCI path; BSP/machine "
                    "recipes supply controller firmware.")
            add_unique(image_pkgs, "bluez5")

    if iot.get("mqtt"):
        add_unique(packageconfig, "mqtt")

    if iot.get("tls"):
        add_unique(packageconfig, "security")
        add_unique(image_pkgs, "ca-certificates")

    if image_pkgs:
        lines.append(f'IMAGE_INSTALL:append = " {" ".join(image_pkgs)}"')
    if packageconfig:
        lines.append(
            f'PACKAGECONFIG:append:pn-alp-sdk = " {" ".join(packageconfig)}"')

    return lines


def _emit_baseline(slice_: Slice, diagnostics: dict[str, Any]) -> list[str]:
    """Baseline Kconfig lines: the fragment header comment + the core
    log/print enables every Zephyr slice gets regardless of what it
    declares in board.yaml.
    """
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/alp_orchestrate.py "
                 "-- do not edit.")
    lines.append(f"# Per-core Kconfig fragment for slice "
                 f"`{slice_.core_id}` ({slice_.os}).")
    lines.append("")
    lines.append("CONFIG_ALP_SDK=y")
    lines.append("CONFIG_LOG=y")
    lines.append("CONFIG_PRINTK=y")
    if diagnostics.get("last_error", True):
        lines.append("CONFIG_THREAD_LOCAL_STORAGE=y")
    log_level = diagnostics.get("log_level")
    if log_level is not None:
        log_level_kc = {
            "error": 1, "warn": 2, "info": 3, "debug": 4, "trace": 4,
        }
        if log_level in log_level_kc:
            lines.append(f"CONFIG_LOG_DEFAULT_LEVEL={log_level_kc[log_level]}")
    lines.append("")
    return lines


def _emit_console(diagnostics: dict[str, Any], slice_: Slice) -> list[str]:
    """Console backend, auto-selected from the slice OS (overridable via
    board.yaml `diagnostics.console:`).  A Zephyr slice defaults to the
    Alp UART console so `west build && attach a terminal` just works;
    a customer on a serial-less bench flips to `ram`.

    `diagnostics.sim_console: true` (issue #686) upgrades the AUTO-resolved
    console of a HEADLESS core (`hw_console: false` -- no HW UART, e.g. the
    RZ/V2N M33 system-manager) to the RAM console, so the studio simulator's
    `uart_socket` isn't silent.  Precedence: an explicit `diagnostics.
    console:` always wins; a core that has a UART console is simulated
    through its real UART node and needs no Kconfig change.
    """
    raw = diagnostics.get("console")
    console = _resolve_console(raw, slice_.os, slice_.hw_console)
    auto = (raw or "auto").strip().lower() == "auto"
    # A headless AUTO core resolves to "none" (above); `sim_console: true`
    # upgrades it to the RAM console so the studio simulator's uart_socket
    # isn't silent (#686).  Precedence: an explicit `diagnostics.console:`
    # (auto == False) always wins and is never upgraded.
    sim = bool(diagnostics.get("sim_console")) and auto \
        and not slice_.hw_console and console == "none"
    if sim:
        console = "ram"
    return _emit_zephyr_console(console, sim_console=sim)


def _emit_som_caps(
    project: "BoardProject",
    silicon: Optional[str],
    kconfig: Optional[str],
) -> list[str]:
    """SoM-capability Kconfig lines: HW-manifest EEPROM wiring, the
    resolved SoM-silicon Kconfig symbol, and the cross-EVK board facade /
    `<alp/soc_caps.h>` capability-restriction selector.
    """
    lines: list[str] = []

    # HW manifest EEPROM: the SoM preset provides the default bus,
    # while board.yaml `features.hw_info.eeprom` can pin the exact
    # app/project address and manifest offset.  Harmless on examples
    # without that bus wired: the read returns NOT_READY and the banner
    # says so.
    hw_info_eeprom = project.hw_info_eeprom_config()
    if hw_info_eeprom is not None:
        source = hw_info_eeprom.get("source")
        if source == "features.hw_info.eeprom":
            lines.append(
                "# HW manifest EEPROM from board.yaml `features.hw_info.eeprom`;")
        else:
            lines.append("# On-module HW manifest EEPROM -> portable bus 0 (alp-i2c0);")
        lines.append("# enables alp_hw_info_read() + the console banner manifest line.")
        lines.append(
            "CONFIG_ALP_SDK_HW_INFO_EEPROM_I2C_BUS_ID="
            f"{hw_info_eeprom['bus_id']}")
        if source == "features.hw_info.eeprom":
            lines.append(
                "CONFIG_ALP_SDK_HW_INFO_EEPROM_ADDR_7BIT="
                f"0x{hw_info_eeprom['addr_7bit']:02x}")
            lines.append(
                "CONFIG_ALP_SDK_HW_INFO_EEPROM_OFFSET="
                f"{hw_info_eeprom['offset']}")
        lines.append("")

    if kconfig:
        lines.append(f"# SoM silicon ({silicon} via {project.sku})")
        lines.append(f"CONFIG_{kconfig}=y")
        lines.append("")

    # Cross-EVK board facade selector (<alp/board.h>).
    # Emitted only when the project resolves to a named board preset
    # (e.g. `preset: e1m-x-evk` -> board_name "E1M-X-EVK").
    # CONFIG_COMPILER_OPT passes the define into every source file the
    # Zephyr build compiles, so the facade header can resolve the
    # correct EVK-specific BOARD_* aliases without per-app prj.conf
    # entries or extra_args.  Inline boards (no preset/name) skip this;
    # native_sim testcases that do need the define set it via extra_args.
    # Per-SKU capability-restriction gate for <alp/soc_caps.h>: emitted
    # ONLY when the SoM preset declares `silicon_capabilities.unpopulated`
    # (no SKU in the current catalogue does), so unrestricted SKUs keep a
    # byte-identical fragment.  Folded into the same CONFIG_COMPILER_OPT
    # string as the board facade define because that Kconfig is
    # single-value (last write wins, not additive).
    som_def = ""
    if som_unpopulated_capabilities(project.som_preset):
        som_def = f"-DALP_SOM_{_som_define_slug(project.sku)}"
    if project.board_name:
        # Cross-EVK board facade selector for <alp/board.h>.  NOTE:
        # CONFIG_COMPILER_OPT is a single-value Kconfig string (last write
        # wins, not additive) -- an app must NOT also set it in prj.conf or
        # this -D is silently dropped; pass extra defines another way.
        lines.append("# Cross-EVK board facade selector (<alp/board.h>);"
                     " CONFIG_COMPILER_OPT is single-value (do not also set in prj.conf).")
        if som_def:
            lines.append("# + ALP_SOM_* capability-restriction gate: this SKU "
                         "leaves silicon capabilities unpopulated "
                         "(SoM preset silicon_capabilities.unpopulated).")
        opt = f"-DALP_BOARD_{_board_define_slug(project.board_name)}"
        if som_def:
            opt = f"{opt} {som_def}"
        lines.append(f'CONFIG_COMPILER_OPT="{opt}"')
        lines.append("")
    elif som_def:
        lines.append("# ALP_SOM_* capability-restriction gate (<alp/soc_caps.h>);"
                     " CONFIG_COMPILER_OPT is single-value (do not also set in prj.conf).")
        lines.append(f'CONFIG_COMPILER_OPT="{som_def}"')
        lines.append("")

    return lines


# Slugs that map to BLOCK_ Kconfig symbols rather than CHIP_.
# These live under blocks/ + <alp/blocks/*.h> because they are
# SDK-level *block* utilities (`alp_button_led_*`, `alp_pdm_mic_*`)
# rather than third-party-IC chip drivers; see blocks/README.md.
_BLOCK_SLUGS = frozenset({"button_led", "pdm_mic"})


def _slug_kconfig(slug: str) -> str:
    """Map a chip/block slug to its Kconfig symbol (CHIP_ or BLOCK_)."""
    kind = "BLOCK" if slug in _BLOCK_SLUGS else "CHIP"
    return f"CONFIG_ALP_SDK_{kind}_{slug.upper()}"


def _resolve_chip_states(project: "BoardProject") -> dict[str, bool]:
    """Final resolved on/off state for every chip/block slug the project
    touches -- the single source of truth `_emit_chips` prints its
    `CONFIG_ALP_SDK_CHIP_*=` lines FROM (so the printed line and this map
    can never disagree by construction) and any other emitter (e.g.
    `_zephyr_iot_kconfig`'s CC3501E Wi-Fi/BLE gate) consults before gating
    a dependent symbol (issue #874).

    Precedence: on-module presence is the physical baseline (always
    True). An explicit `populated: {chip: true/false}` entry then applies
    the board's stated population, on-module chip or not. Finally, a
    project-declared `chips:` entry can still turn a board-DNI'd chip ON
    -- the documented escape hatch for a project that wires up a sensor
    the board preset doesn't populate by default (e.g. `ai/cold-chain-
    monitor`'s `chips: [bme280]` overriding the EVK preset's `populated:
    {bme280: false}`) -- UNLESS the chip is ALSO on-module: an on-module
    (SoM-intrinsic) component is fixed at SoM-fab time (see the `som:`
    block's own description in board.schema.json) and re-listing it in
    `chips:` is a redundant declaration, not a fresh override, so it must
    not silently flip a board's `populated: {chip: false}` back on for a
    chip ALSO claimed on-module (issue #874 follow-up: the triple-overlap
    case -- on-module + populated:false + project `chips:` all naming the
    same chip -- used to let the project-chips pass win regardless,
    re-creating the exact WIFI_CC3501E=y-against-chip=n contradiction
    #874 fixed).
    """
    states: dict[str, bool] = {}

    som_chips: set[str] = set()
    om = project.som_preset.get("on_module") or {}
    for slug in _slugs_from_on_module(om):
        som_chips.add(slug)
    hf = project.som_preset.get("helper_firmware") or []
    for slug in _slugs_from_helper_firmware(hf):
        som_chips.add(slug)
    for chip in som_chips:
        states[chip] = True

    populated: dict[str, bool] = dict(
        (project.board_preset or {}).get("populated") or {})
    for chip, on in populated.items():
        states[chip] = bool(on)

    for chip in (project.chips or []):
        if chip in som_chips:
            continue
        states[chip] = True

    return states


def _emit_chips(
    project: "BoardProject",
    chip_subsystems_table: dict[str, tuple[str, ...]],
) -> tuple[list[str], set[str], dict[str, bool]]:
    """SoM-intrinsic + board-populated + project-declared chip drivers.

    Every `CONFIG_ALP_SDK_CHIP_*=` / `CONFIG_ALP_SDK_BLOCK_*=` line is
    printed FROM `_resolve_chip_states`'s resolved map (single source of
    truth, issue #874) and printed EXACTLY ONCE regardless of how many of
    the three sources below mention it -- a chip already printed by an
    earlier block is skipped by a later one rather than re-asserted with
    a value that could disagree.

    Returns the emitted Kconfig lines, the accumulated set of Zephyr
    subsystem names the enabled chip drivers require -- fed into
    `_emit_subsystems` alongside the slice's `peripherals:` array -- and
    the resolved chip on/off map.
    """
    lines: list[str] = []
    chip_subsystems: set[str] = set()
    resolved_chip_state = _resolve_chip_states(project)
    printed: set[str] = set()

    def _emit_block(header: str, candidates) -> None:
        chips = sorted(c for c in set(candidates) if c not in printed)
        if not chips:
            return
        lines.append(header)
        for chip in chips:
            on = resolved_chip_state.get(chip, False)
            lines.append(f"{_slug_kconfig(chip)}={'y' if on else 'n'}")
            printed.add(chip)
            if on:
                for s in chip_subsystems_table.get(chip, ()):
                    chip_subsystems.add(s)
        lines.append("")

    # ----------------------------------------------------------------
    # SoM-intrinsic chip drivers — derived from on_module: + helper_firmware:
    # in the SoM preset.  These are NOT declared by the customer; they
    # are determined by which SoM SKU the project targets.  Swapping
    # `som.sku:` from E1M-V2N101 to E1M-AEN801 automatically swaps
    # the on-module chip set without any board.yaml changes.
    # ----------------------------------------------------------------
    som_chips: set[str] = set()
    om = project.som_preset.get("on_module") or {}
    if om:
        for slug in _slugs_from_on_module(om):
            som_chips.add(slug)
    hf = project.som_preset.get("helper_firmware") or []
    for slug in _slugs_from_helper_firmware(hf):
        som_chips.add(slug)

    _emit_block(
        f"# SoM-intrinsic chip drivers (from `{project.sku}` "
        f"on_module + helper_firmware)", som_chips)

    # ----------------------------------------------------------------
    # Board-populated chip drivers.  Single source: the resolved
    # board_preset dict, which comes from either the shared
    # metadata/boards/<preset>.yaml or the project's inline
    # top-level fields (synthesised by the loader).  No project-level
    # override merge -- the schema's `oneOf` rule rejects mixing.
    #
    # Chip drivers compile per-chip via the
    # zephyr_library_sources_ifdef(CONFIG_ALP_SDK_CHIP_<NAME> ...)
    # (or CONFIG_ALP_SDK_BLOCK_<NAME> for the `button_led` / `pdm_mic`
    # SDK-level block helpers) entries in zephyr/CMakeLists.txt.
    #
    # We emit the chip-driver block on every zephyr slice — Kconfig
    # dedupes when multiple per-core fragments overlay onto the same
    # base.  This keeps `--core <id>` invocations self-sufficient
    # (the slice carries everything it needs to compile) without
    # depending on cross-slice ordering.
    # ----------------------------------------------------------------
    populated: dict[str, bool] = dict(
        (project.board_preset or {}).get("populated") or {})
    _emit_block(
        "# Board-populated chip drivers (from the resolved "
        "board definition)", populated.keys())

    # Project-declared chips (board.yaml top-level `chips:` array).
    # Adds chip drivers the application links directly via
    # <alp/chips/<name>.h> -- e.g. when the project plugs an external
    # sensor into a board's headers that's not in the board's
    # `populated:` table, or turns ON a chip the board preset DNIs by
    # default (`_resolve_chip_states` already folded that override into
    # the resolved value the "Board-populated" block above printed, so
    # there is nothing left to print here for such a chip -- this block
    # only has fresh lines for chips `populated:` never mentioned at
    # all).  A chip that's ALSO on-module never reaches here with a
    # different value than the SoM-intrinsic block already printed
    # (`_resolve_chip_states` deliberately does not let a project
    # `chips:` entry override an on-module chip's resolved state).
    _emit_block(
        "# Project-declared chips (board.yaml `chips:` array)",
        project.chips or [])

    return lines, chip_subsystems, resolved_chip_state


def _emit_subsystems(slice_: Slice, chip_subsystems: set[str]) -> list[str]:
    """Zephyr subsystems required by the slice: union of (chip-driver-
    required subsystems, from `_emit_chips`) and (this core's
    `peripherals:` array, which adds to the union per spec §4.6).
    """
    lines: list[str] = []
    periph_subsystems: set[str] = set()
    for periph in slice_.peripherals or []:
        periph_subsystems.update(_PERIPHERAL_KCONFIG.get(periph, ()))
    all_subsystems = chip_subsystems | periph_subsystems
    if all_subsystems:
        lines.append(f"# Zephyr subsystems required on core "
                     f"`{slice_.core_id}` (chip drivers + peripherals)")
        for s in sorted(all_subsystems):
            lines.append(f"CONFIG_{s}=y")
        lines.append("")
    return lines


def _library_alias_table() -> dict[str, str]:
    """Legacy per-core `libraries:` token -> canonical manifest name
    (metadata/library-aliases-v1.json).  Empty dict if the table is absent."""
    path = METADATA_ROOT / "library-aliases-v1.json"
    if not path.is_file():
        return {}
    doc = json.loads(path.read_text(encoding="utf-8"))
    aliases = doc.get("aliases")
    return dict(aliases) if isinstance(aliases, dict) else {}


def _per_core_library_kconfig(lib: str) -> Optional[list[str]]:
    """Base-Kconfig lines for a per-core `libraries:` token, read from the
    library's ADR 0018 manifest (metadata/libraries/<canonical>.yaml) rather
    than a hand-maintained table (WS6-c #610 §6).

    The token is resolved to its canonical manifest through the
    metadata/library-aliases-v1.json alias table.  The emitted set is the union
    of the manifest's `integration.zephyr.kconfig` (the upstream module-enable
    line(s)) and its `integration.zephyr.hw_backends.sw_fallback.kconfig` (the
    SDK SW floor), module-enable first and the SW-fallback marker last, deduped.
    Header-only libraries whose SW floor is a doc comment surface that comment.

    Returns None when no manifest resolves (caller emits the pending-wire TODO).
    """
    alias = _library_alias_table()
    canonical = alias.get(lib, lib)
    path = METADATA_ROOT / "libraries" / f"{canonical}.yaml"
    if not path.is_file():
        return None
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    zephyr = (doc.get("integration") or {}).get("zephyr") or {}
    out: list[str] = []
    for kc in (zephyr.get("kconfig") or []):
        kc = str(kc)
        if kc not in out:
            out.append(kc)
    swf = ((zephyr.get("hw_backends") or {}).get("sw_fallback") or {}).get("kconfig")
    if swf:
        swf = str(swf)
        if swf.lstrip().startswith("#"):
            # Header-only library: the SW floor is a documentation comment,
            # not a real knob.  Surface it only when there is no module enable.
            if not out:
                out.append(swf)
        elif swf not in out:
            out.append(swf)
    return out


def _emit_libraries(
    project: "BoardProject",
    slice_: Slice,
) -> list[str]:
    """Per-core `libraries:`, curated third-party `libraries:` (ADR 0018),
    and the open-set `extra_libraries:` escape hatch (v0.6 P2.1).

    Per-core Kconfig is resolved from each library's manifest
    (`_per_core_library_kconfig`), not a hand-maintained enable table.
    """
    lines: list[str] = []

    if slice_.libraries:
        lines.append(f"# Libraries declared on core "
                     f"`{slice_.core_id}`")
        for lib in sorted(slice_.libraries):
            kcs = _per_core_library_kconfig(lib)
            if kcs is None:
                lines.append(
                    f"# TODO: wire library '{lib}' once its v0.4 enable lands")
            else:
                for kc in kcs:
                    lines.append(kc)
        lines.append("")

    # Project-wide curated third-party libraries (top-level `libraries:`,
    # ADR 0018).  Emitted from the metadata/libraries/<name>.yaml manifests;
    # resolve_selection() has already rejected any incompatible selection.
    # Guard keeps a project with no `libraries:` byte-identical.
    library_lines = _library_layer.zephyr_kconfig_lines(project, slice_)
    if library_lines:
        lines.append("# Curated third-party libraries "
                     "(project `libraries:`, ADR 0018)")
        lines.extend(library_lines)
        lines.append("")

    # ----------------------------------------------------------------
    # Open-set extra_libraries (v0.6 P2.1).  Each entry declares either
    # inline `kconfig:` lines (emitted verbatim) or a `profile:` path
    # to a hw-backends.yaml-style file we walk with the same silicon /
    # soc_family / requires_cap matcher as the curated libraries.
    # _validate_consistency() guarantees exactly-one of kconfig/profile
    # and the profile file resolves, so the per-entry checks here are
    # just for emit-time safety.
    # ----------------------------------------------------------------
    if slice_.extra_libraries:
        lines.append(f"# Extra libraries declared on core "
                     f"`{slice_.core_id}` (open-set escape hatch)")
        for entry in sorted(slice_.extra_libraries,
                            key=lambda e: e.get("name", "")):
            name = entry.get("name", "<unnamed>")
            kc_lines = entry.get("kconfig")
            profile = entry.get("profile")
            if kc_lines:
                lines.append(f"# extra_libraries[{name}] (inline kconfig)")
                for kc in kc_lines:
                    lines.append(str(kc))
            elif profile:
                lines.append(f"# extra_libraries[{name}] (profile: {profile})")
                profile_lines = _emit_extra_library_profile(
                    name, profile, project)
                if profile_lines:
                    lines.extend(profile_lines)
                else:
                    lines.append(
                        f"# (no matching backend for "
                        f"silicon={project.som_preset.get('silicon')} "
                        f"in {profile})")
        lines.append("")

    return lines


def _slice_wants_inference(slice_: Slice) -> bool:
    """True when this slice genuinely uses `<alp/inference.h>`.

    Two independent signals, either sufficient: `cores.<id>.inference:`
    declared (app-level tuning, e.g. `default_arena_kib:` -- the signal
    every inference example under examples/ai, examples/audio,
    examples/camera-vision declares), OR the slice's own `libraries:`
    pulls in `tflite-micro` (resolved through the same alias table
    `_per_core_library_kconfig` uses -- a `cores:`-scoped top-level
    `libraries:` entry folds into `slice_.libraries` at load time, see
    `loader.py::_normalize_libraries`). The library signal exists because
    `cores.<id>.inference:` is app-level TUNING, not a declaration of
    intent -- an app that never overrides the arena default has no reason
    to write the block, and #874's adversarial follow-up found exactly
    that false negative (`examples/camera-vision/
    ai-object-detection-realtime`, `libraries: tflite-micro` with no
    `inference:` block). A slice with NEITHER signal stays clean (no
    unconditional emit returns, issue #874 item 4).
    """
    if slice_.inference:
        return True
    alias = _library_alias_table()
    return any(alias.get(lib, lib) == "tflite-micro"
               for lib in (slice_.libraries or ()))


def _emit_inference(
    project: "BoardProject",
    slice_: Slice,
    silicon: Optional[str],
) -> list[str]:
    """Inference dispatcher enables, driven entirely by the SoM preset's
    `capabilities:` matrix + SoC-JSON `cores[]` -- NOT by board.yaml.
    The customer never picks *which backend* at build time; the SDK
    compiles in every dispatcher the silicon supports, and apps choose
    per-handle at runtime via alp_inference_open(.backend=...).
    CPU/TFLM is the universal SW fallback and is on whenever this
    section emits at all.

    *Whether* the section emits anything is gated on `_slice_wants_inference`
    (declared `cores.<id>.inference:` tuning OR a `libraries:` pull of
    `tflite-micro`).  Emitting the backend switches unconditionally on
    every zephyr slice used to put a misleading `=y` line (silently
    resolving to n -- BACKEND_TFLM's `depends on TENSORFLOW_LITE_MICRO &&
    CPP` are genuinely-external symbols not every slice's prj.conf sets)
    in front of apps that never call alp_inference_open() at all
    (issue #874).

    Two layers of variant detail are emitted alongside the umbrella
    switches so the SDK driver code + (upstream) kernel libraries
    compile against the right per-silicon variant, each only alongside
    the ALP_SDK_* parent it `depends on` in
    zephyr/kconfigs/iot-audio-inference.kconfig (issue #874 item 3):

      - CONFIG_ALP_SDK_INFERENCE_ETHOS_U_U{55,65,85}=y -- derived from
        the silicon capability counts (ethos_u{55,65,85}_count, resolved
        from the SoC JSON npus[]), the single source for which NPUs the
        part carries.  U85 carries Arm's larger MAC array + TensorOptimized
        kernels; U55 carries the smaller MAC + reference kernels; U65 is
        i.MX 93-only.  U55/U85 depend on BACKEND_ETHOS_U_AEN; U65 depends
        on BACKEND_ETHOS_U_N93.

      - CONFIG_ALP_SDK_INFERENCE_TFLM_{NEON,HELIUM,REF}=y -- picked
        from the SoC JSON's `cores[<slice.core_id>].vector_extension`
        so the CPU-side TFLM kernel set matches the target core's SIMD
        reality (NEON on A-cluster, Helium MVE on M55, scalar / REF
        on baseline M33 / M4).  Per-core in case a single SoM hosts
        multiple core classes (E7 = A32 + M55, all three Helium /
        Neon flavours).  All three depend on BACKEND_TFLM.
    """
    if not _slice_wants_inference(slice_):
        return []

    lines: list[str] = []

    # resolve_capabilities merges SoC-JSON defaults with SoM overrides
    # so silicon-determined caps (ethos_u55_count, drp_ai, ...) resolve
    # even when removed from the SoM YAML (capability unification, slice 3b).
    capabilities = resolve_capabilities(project.som_preset, METADATA_ROOT)
    inference_lines: list[str] = [
        # BACKEND_TFLM depends on TENSORFLOW_LITE_MICRO && CPP -- genuinely
        # external (upstream Zephyr / tflite-micro module) symbols, not
        # ALP_SDK_*.  west.yml pulls the tflite-micro module in
        # unconditionally (no west group gate; see west.yml's
        # name-allowlist), so both resolve here rather than requiring every
        # inference app to hand-write them in its own prj.conf (#874; see
        # also #855 for cross-alp-sdk-version symbol skew).  This is
        # effective on an alp-sdk-topdir west workspace (west.yml's own
        # manifest); a workspace initialised off a bare upstream
        # `zephyr` manifest (the repo's own twister CI, a plain
        # `west init -m .../zephyr`) has no tflite-micro module at all,
        # so TENSORFLOW_LITE_MICRO degrades gracefully to n (a Kconfig
        # "assigned y but got n" warning, not fatal -- the inference
        # dispatcher falls back to ALP_SDK_INFERENCE_SW_FALLBACK there).
        "CONFIG_CPP=y",
        # tflite-micro's headers require C++17 (e.g. tensorflow/lite/array.h
        # uses std::conditional_t / std::decay_t).  Zephyr's C++ standard
        # `choice STD_CPP` defaults to C++11, so a TFLM build compiled at
        # -std=c++11 fails.  Emit C++17 here whenever inference (TFLM) is
        # wanted so every inference project builds without hand-editing:
        # real NPU apps previously set CONFIG_STD_CPP17=y in their own
        # prj.conf; the emit now guarantees it on every platform (native_sim
        # + real silicon alike), matching what the AEN NPU builds already use.
        "CONFIG_STD_CPP17=y",
        "CONFIG_TENSORFLOW_LITE_MICRO=y",
        "CONFIG_ALP_SDK_INFERENCE_BACKEND_TFLM=y",
    ]

    # ---- G-2 -- CPU-class TFLM kernel selector --------------------
    # Look up this slice's core in the SoC spec; pick exactly one of
    # NEON / HELIUM / REF based on the vector_extension field.  Defaults
    # to REF when the SoC JSON is silent (paper-correct on the scalar
    # M33s -- iMX 93 m33, V2N m33_sm).
    tflm_kernel_kc: str = "CONFIG_ALP_SDK_INFERENCE_TFLM_KERNEL_REF=y"
    for c in (project.soc_spec.get("cores") or []):
        if c.get("id") != slice_.core_id:
            continue
        vec = (c.get("vector_extension") or "").lower()
        ctype = (c.get("type") or "").lower()
        if vec == "neon" or ctype.startswith("cortex-a"):
            tflm_kernel_kc = "CONFIG_ALP_SDK_INFERENCE_TFLM_KERNEL_NEON=y"
        elif vec == "helium":
            tflm_kernel_kc = "CONFIG_ALP_SDK_INFERENCE_TFLM_KERNEL_HELIUM=y"
        else:
            tflm_kernel_kc = "CONFIG_ALP_SDK_INFERENCE_TFLM_KERNEL_REF=y"
        break
    inference_lines.append(tflm_kernel_kc)

    # ---- G-1 -- per-variant Ethos-U selector ---------------------
    # Which Ethos-U variants this SoM carries -- derived from the
    # silicon-determined capability counts (ethos_u{55,65,85}_count, resolved
    # from the SoC JSON npus[] via resolve_capabilities).  This is the single
    # source: an on-die NPU cannot be depopulated at the SoM level, so the SoM
    # preset does NOT restate the variant list (the SoM `inference.npu_population`
    # field is deprecated and no longer read here).
    ethos_variants: set[str] = set()
    if (capabilities.get("ethos_u55_count") or 0) > 0:
        ethos_variants.add("u55")
    if (capabilities.get("ethos_u65_count") or 0) > 0:
        ethos_variants.add("u65")
    if (capabilities.get("ethos_u85_count") or 0) > 0:
        ethos_variants.add("u85")
    ethos_present = bool(ethos_variants)
    if ethos_present:
        # Per-silicon Ethos-U backend (Slice 3 registry layout):
        # Alif Ensemble (AEN) -> _BACKEND_ETHOS_U_AEN
        # NXP i.MX 93        -> _BACKEND_ETHOS_U_N93
        # Parent-gating (#874 item 3): only emit the variant switches that
        # `depend on` the parent backend we're actually emitting on this
        # silicon -- U55/U85 depend on BACKEND_ETHOS_U_AEN, U65 depends on
        # BACKEND_ETHOS_U_N93 (zephyr/kconfigs/iot-audio-inference.kconfig).
        if silicon == "nxp:imx9:imx93":
            inference_lines.append("CONFIG_ALP_SDK_INFERENCE_BACKEND_ETHOS_U_N93=y")
            allowed_variants = {"u65"}
        else:
            inference_lines.append("CONFIG_ALP_SDK_INFERENCE_BACKEND_ETHOS_U_AEN=y")
            allowed_variants = {"u55", "u85"}
        for v in sorted(ethos_variants & allowed_variants):
            inference_lines.append(f"CONFIG_ALP_SDK_INFERENCE_ETHOS_U_VARIANT_{v.upper()}=y")
        # Real Arm Ethos-U driver config -- the silicon-proven pair (bench:
        # E1M-AEN801/E8, person_detect U85).  BACKEND_ETHOS_U_AEN already
        # `select ETHOS_U if DT_HAS_ARM_ETHOS_U_ENABLED` (silicon-only); these
        # assignments complete the driver config.  The core driver compiles
        # exactly ONE accelerator config (ETHOS_U_NPU_CONFIG is a Kconfig
        # `choice`), so pick the single most-capable NPU this silicon carries.
        # On native_sim (no arm,ethos-u node) ETHOS_U stays off, so the
        # ETHOS_U*-dependent lines below no-op with a harmless Kconfig
        # "assigned y but got n" warning (same pattern as TENSORFLOW_LITE_MICRO
        # above).  CONFIG_ETHOS_U_DCACHE=y links the correct-signature dcache
        # hooks (NOT CONFIG_ARM_ETHOS_U -- hal_alif's stale callback path);
        # CONFIG_DCACHE=n is the CPU<->NPU SRAM coherence mechanism; the
        # ethos_u driver's mutex/semaphore need a kernel heap (k_malloc).
        # Pick the most-capable variant this silicon carries (U85 > U65 > U55),
        # then read its MAC config from the SoC's npus[] `mac_per_cycle` -- NOT a
        # hardcode.  The derived symbol must be a real ETHOS_U_NPU_CONFIG choice
        # member (hal_ethos_u), else it would silently no-op -- so validate and
        # fail loudly on a metadata mismatch.
        if "u85" in ethos_variants:
            variant_num = "85"
        elif "u65" in ethos_variants:
            variant_num = "65"
        else:
            variant_num = "55"
        npu_type = f"ethos-u{variant_num}"
        npus_of_type = [
            n for n in (project.soc_spec.get("npus") or [])
            if str(n.get("type", "")).lower() == npu_type and n.get("mac_per_cycle")
        ]
        # Size the accelerator for the NPU instance THIS slice's core actually
        # drives, not the SoC's most-capable one.  A part can carry two U55s of
        # the same variant but different MACs wired to different cores (E3/E5/E7:
        # a 256-MAC high-perf U55 on M55-HP + a 128-MAC high-efficiency U55 on
        # M55-HE -- npus[].paired_core in the SoC JSON).  A 256-MAC command
        # stream errors a 128-MAC NPU at invoke (register-proven on E8), so a
        # blind max() would mis-size the HE slice.  Prefer the core-paired
        # instance; fall back to the most-capable of the variant when the chosen
        # variant is not core-paired (the E8 U85 on the shared HG subsystem) or
        # the SoC JSON predates paired_core.
        paired = [n["mac_per_cycle"] for n in npus_of_type
                  if n.get("paired_core") == slice_.core_id]
        macs   = [n["mac_per_cycle"] for n in npus_of_type]
        if paired:
            mac = paired[0]
        elif len({*macs}) > 1:
            # This variant has >1 distinct MAC array on the SoC but none is
            # paired_core=<this slice's core> -- a silent max() here would
            # re-introduce the #909 mis-sizing (a 256-MAC command stream errors
            # a 128-MAC NPU at invoke).  Fail loudly, like the _valid_accel
            # guard below, so a missing/typo'd paired_core is caught at emit.
            raise ValueError(
                f"{silicon}: inference slice core {slice_.core_id!r} drives an "
                f"{npu_type} but the SoC JSON declares MAC variants {sorted({*macs})} "
                f"and none sets paired_core={slice_.core_id!r} -- add "
                f"npus[].paired_core so the build sizes the accelerator for this "
                f"core instead of guessing (see #909).")
        else:
            # Single MAC for this variant (or npus[]-less older spec): unambiguous.
            mac = macs[0] if macs else 256
        accel = f"ETHOS_U{variant_num}_{mac}"
        _valid_accel = {
            "ETHOS_U55_64", "ETHOS_U55_128", "ETHOS_U55_256",
            "ETHOS_U65_128", "ETHOS_U65_256", "ETHOS_U65_512",
            "ETHOS_U85_128", "ETHOS_U85_256", "ETHOS_U85_512",
            "ETHOS_U85_1024", "ETHOS_U85_2048",
        }
        if accel not in _valid_accel:
            raise ValueError(
                f"{silicon}: derived Ethos-U accelerator {accel!r} "
                f"(npus[].mac_per_cycle={mac} for {npu_type}) is not a valid "
                f"ETHOS_U_NPU_CONFIG choice member -- check the SoC JSON npus[]")
        inference_lines.append("CONFIG_ETHOS_U_DCACHE=y")
        inference_lines.append(f"CONFIG_{accel}=y")
        inference_lines.append("CONFIG_DCACHE=n")
        inference_lines.append("CONFIG_HEAP_MEM_POOL_SIZE=65536")
    # DRP-AI3 and DEEPX DX-M1 have NO Zephyr Kconfig -- deliberately.
    # Both engines are A55/Linux-side only (DRP-AI3 via the MERA/TVM
    # userspace runtime, DX-M1 via libdxrt over the A55's PCIe); an
    # M-class Zephyr slice cannot drive either (issues #58/#59), so it
    # gets TFLM only.  Their build wiring lives on the cmake-args /
    # Yocto emit paths (_slice_cmake_args below).
    lines.append("# Inference dispatchers (from SoM capabilities -- "
                 "customer does not pick)")
    lines.extend(inference_lines)
    lines.append("")
    return lines


def _emit_memory(slice_: Slice) -> list[str]:
    """Per-slice memory tuning (board.yaml `cores.<id>.memory:`)."""
    lines: list[str] = []
    mem = slice_.memory or {}
    mem_lines: list[str] = []
    if mem.get("stack_kib"):
        mem_lines.append(f"CONFIG_MAIN_STACK_SIZE={int(mem['stack_kib']) * 1024}")
    if mem.get("isr_stack_kib"):
        mem_lines.append(f"CONFIG_ISR_STACK_SIZE={int(mem['isr_stack_kib']) * 1024}")
    if mem.get("heap_kib") is not None:
        mem_lines.append(f"CONFIG_HEAP_MEM_POOL_SIZE={int(mem['heap_kib']) * 1024}")
    if mem_lines:
        lines.append("# Per-slice memory tuning (board.yaml cores.<id>.memory:)")
        lines.extend(mem_lines)
        lines.append("")
    return lines


def _emit_power(slice_: Slice) -> list[str]:
    """Per-slice power-management profile (board.yaml `cores.<id>.power:`)."""
    lines: list[str] = []
    pwr = slice_.power or {}
    pwr_lines: list[str] = []
    sleep_mode = (pwr.get("sleep_mode") or "disabled").lower()
    if sleep_mode != "disabled":
        pwr_lines.append("CONFIG_PM=y")
        pwr_lines.append("CONFIG_PM_DEVICE=y")
        # PM_STATE_* selection is silicon-family-specific; lowest-power
        # state the hierarchy keeps is mirrored in a single hint flag.
        pwr_lines.append(f"# Sleep target: {sleep_mode}")
    for wake in (pwr.get("wakeup_sources") or []):
        # Wake-source declarations land as hint comments only.  Zephyr
        # marks a device as wakeup-capable via the DT `wakeup-source;`
        # property + a runtime pm_device_wakeup_enable() call; there is
        # no top-level CONFIG_PM_DEVICE_WAKE_<SUBSYS> Kconfig symbol, so
        # emitting one trips the build with `undefined symbol` warnings
        # (-> kconfig errors -> twister CMake build failure).  The real
        # DT-overlay + runtime-enable plumbing lands per silicon in v0.7;
        # until then the wake-source list is documented in the generated
        # alp.conf for the customer to wire by hand.
        if isinstance(wake, str) and not wake.startswith("E1M_"):
            pwr_lines.append(
                f"# wakeup source: {wake} "
                "(DT wakeup-source; + pm_device_wakeup_enable() pending v0.7)")
        elif isinstance(wake, str):
            pwr_lines.append(f"# wakeup source: {wake} (per-silicon Kconfig pending)")
    if pwr_lines:
        lines.append("# Per-slice power-management profile (board.yaml cores.<id>.power:)")
        lines.extend(pwr_lines)
        lines.append("")
    return lines


def _emit_storage(project: "BoardProject") -> list[str]:
    """Storage partitions (board.yaml `storage:` block).  Emits per-fs
    Kconfig for every resolved (non-blocked) partition.  Blocked
    partitions produce a hint comment so the slice build still
    compiles but the runtime mount fails loudly via the DTS overlay.

    Per-slice ownership of partitions is not modelled today: every
    Zephyr/baremetal slice gets the union.  Kconfig dedupes when
    multiple per-core fragments overlay onto the same base.  v0.7
    may add `core:` to storage entries for per-slice scoping.
    """
    lines: list[str] = []
    partitions = resolve_storage_partitions(project)
    ok_partitions = [p for p in partitions if p.status == "ok"]
    fs_seen: set[str] = set()
    for p in ok_partitions:
        fs_seen.add(p.fs)
    fs_kconfig: list[str] = []
    if "littlefs" in fs_seen:
        fs_kconfig.append("CONFIG_FILE_SYSTEM=y")
        fs_kconfig.append("CONFIG_FILE_SYSTEM_LITTLEFS=y")
    if "fat" in fs_seen:
        fs_kconfig.append("CONFIG_FILE_SYSTEM=y")
        fs_kconfig.append("CONFIG_FAT_FILESYSTEM_ELM=y")
    if "ext4" in fs_seen:
        fs_kconfig.append("CONFIG_FILE_SYSTEM=y")
        fs_kconfig.append("CONFIG_FILE_SYSTEM_EXT2=y")
    if fs_kconfig or ok_partitions:
        lines.append("# Storage partitions (board.yaml `storage:`)")
        # FILE_SYSTEM=y appears twice in the list when multiple fs
        # types are enabled; dedupe before emit.
        for kc in sorted(set(fs_kconfig)):
            lines.append(kc)
        # Per-partition LITTLEFS partition labels surface as a hint
        # comment only.  Modern Zephyr does NOT define a per-partition
        # CONFIG_FS_LITTLEFS_PARTITION_<NAME> Kconfig -- the partition
        # gets matched via the DT `fixed-partitions` node + the
        # chosen `zephyr,storage-partition` / FIXED_PARTITION_ID()
        # macro at runtime.  Emitting a Kconfig stem trips Zephyr's
        # "assignment to undefined symbol" warning + aborts the build.
        for p in ok_partitions:
            if p.fs == "littlefs":
                lines.append(
                    f"# partition[{p.name}] -> mount at runtime via "
                    f"FIXED_PARTITION_ID({p.name}_partition)")
        blocked = [p for p in partitions if p.status == "blocked"]
        for p in blocked:
            lines.append(f"# BLOCKED storage[{p.name}]: "
                         f"{p.reason or 'unknown reason'}")
        lines.append("")
    return lines


def _emit_ota(project: "BoardProject") -> list[str]:
    """OTA Zephyr client (board.yaml `ota:` block, provider-driven dispatch).

    Resolved design Q on the Zephyr-side OTA client (ADR 0009 follow-up):
      provider: mender   -> Mender-MCU-client (out-of-tree, BSD-3)
      provider: hawkbit  -> Zephyr Hawkbit DDI client (upstream)
      provider: mcumgr   -> Zephyr MCUmgr (upstream; transport is the app's call)

    Yocto slices keep the existing Mender server-mode dispatch in
    `_slice_local_conf`.  This handles the Zephyr side: per-slice
    Kconfig that compiles the matching client in.  Settings (server URL,
    poll interval, tenant token) thread through Kconfig string values
    when declared in `ota:`; placeholders (${VAR}) pass through verbatim
    so the build system substitutes at link time.
    """
    lines: list[str] = []
    ota = project.ota or {}
    provider = (ota.get("provider") or "").lower() if isinstance(ota, dict) else ""
    if provider and provider in ("mender", "hawkbit", "mcumgr"):
        lines.append(f"# OTA Zephyr client (board.yaml `ota.provider: {provider}`)")
        srv = (ota.get("server") or {}) if isinstance(ota.get("server"), dict) else {}
        poll = ota.get("poll_interval_s")
        if provider == "mender":
            # Mender-MCU-client.  The west.yml `mender` group is NOT
            # active by default (the upstream mender-mcu-client
            # repository is pinned alongside the v0.7 OTA wiring), so
            # CONFIG_MENDER_* would resolve to undefined-symbol warnings
            # under twister and abort the build.  Emit the settings as
            # hint comments so the configuration is visible to the
            # customer (and to anyone reviewing the generated alp.conf)
            # while keeping the build clean.  When the mender west
            # group flips active the comments here go back to live
            # CONFIG_* lines in a single commit.
            lines.append("# Mender-MCU-client wiring is pending the v0.7 OTA module")
            lines.append("# (mender-mcu-client west group activation).")
            lines.append("# CONFIG_MENDER_MCU_CLIENT=y")
            if srv.get("url"):
                lines.append(f'# CONFIG_MENDER_SERVER_URL="{srv["url"]}"')
            if srv.get("tenant"):
                lines.append(f'# CONFIG_MENDER_TENANT_TOKEN="{srv["tenant"]}"')
            if ota.get("artifact_name"):
                lines.append(f'# CONFIG_MENDER_ARTIFACT_NAME="{ota["artifact_name"]}"')
            if isinstance(poll, int) and poll > 0:
                lines.append(f"# CONFIG_MENDER_UPDATE_POLL_INTERVAL={poll}")
        elif provider == "hawkbit":
            # Zephyr upstream's Hawkbit DDI client.
            lines.append("CONFIG_HAWKBIT=y")
            lines.append("CONFIG_HAWKBIT_SHELL=y")
            if srv.get("url"):
                lines.append(f'CONFIG_HAWKBIT_SERVER="{srv["url"]}"')
            if isinstance(poll, int) and poll > 0:
                lines.append(f"CONFIG_HAWKBIT_POLL_INTERVAL={poll}")
        elif provider == "mcumgr":
            # MCUmgr is upstream; the transport (UART/BLE/UDP) stays the
            # app's call -- we only enable the base SMP server.
            lines.append("CONFIG_MCUMGR=y")
            lines.append("CONFIG_MCUMGR_GRP_IMG=y")
            lines.append("CONFIG_MCUMGR_GRP_OS=y")
            lines.append("# MCUmgr transport (UART/BLE/UDP) is the app's call;")
            lines.append("# enable the matching CONFIG_MCUMGR_TRANSPORT_* in your prj.conf.")
        lines.append("")
    return lines


def _emit_diagnostics(project: "BoardProject") -> list[str]:
    """Per-module log-level overrides (board.yaml `diagnostics.modules:`).

    Zephyr's per-module CONFIG_<MOD>_LOG_LEVEL symbol exists only when
    the matching module has called LOG_MODULE_REGISTER() at build time.
    ALP_* SDK-side modules have not registered any LOG modules yet, so
    emitting `CONFIG_ALP_<MOD>_LOG_LEVEL=N` trips the Zephyr build with
    `undefined symbol ALP_<MOD>_LOG_LEVEL`.  We restrict the active
    emit to modules whose Kconfig declaration is known to exist and
    downgrade ALP_* + unknown modules to a hint comment until their
    LOG_MODULE_REGISTER call lands.
    """
    lines: list[str] = []
    modules = (project.diagnostics or {}).get("modules") or {}
    if modules:
        level_to_n = {"off": 0, "error": 1, "warn": 2, "info": 3, "debug": 4, "trace": 4}
        lines.append("# Per-module log-level overrides (board.yaml diagnostics.modules:)")
        for mod, lvl in sorted(modules.items()):
            n = level_to_n.get(str(lvl).lower())
            if n is None:
                continue
            kc_stem = mod.upper()
            if kc_stem.startswith("ALP_"):
                lines.append(
                    f"# CONFIG_{kc_stem}_LOG_LEVEL={n} "
                    "(pending LOG_MODULE_REGISTER on this SDK module)")
            else:
                lines.append(f"CONFIG_{kc_stem}_LOG_LEVEL={n}")
        lines.append("")
    return lines


def _slice_alp_conf(project: BoardProject, slice_: Slice) -> str:
    """Per-core Kconfig fragment for a Zephyr slice.

    Emits the full Kconfig the slice needs: baseline + log + silicon +
    per-core peripherals/libraries + SoM-intrinsic chip drivers (auto-
    derived from ``on_module:`` + ``helper_firmware:`` in the SoM preset)
    + board-populated chip drivers (from board.yaml ``board.populated:``
    + the board preset) + the Zephyr subsystem enables those chip drivers
    need (e.g. an enabled ``rv3028c7`` chip driver pulls in ``CONFIG_I2C=y``).

    Swapping ``som.sku:`` in board.yaml automatically changes the SoM-
    intrinsic chip set with no other board.yaml edits required.

    This is a thin composer: each section below is delegated to a
    dedicated ``_emit_*`` helper (console / SoM capability / chip driver
    / subsystem / library / inference / memory / power / storage / OTA /
    diagnostics), called in the exact fixed order the fragment has
    always used. Split out mechanically as the #673 Phase-1 kconfig
    split -- behavior-preserving; emit output is byte-identical to the
    pre-split monolith (see ``check_emit_snapshots.py``).
    """
    silicon = project.som_preset.get("silicon")
    kconfig = silicon_to_kconfig(silicon)
    diagnostics = project.diagnostics

    # Lazy-import alp_project tables — in alp-sdk alp_project imports us, so a
    # top-level import would cycle.  Only paid when emitting Zephyr fragments.
    # RELOCATED: the scripts/ dir used to be one parent up from this file; it is
    # now the BOUND SDK checkout's scripts/, which `bind_sdk_root` already put on
    # sys.path (this keeps the guard so the lazy path is self-sufficient).
    import sys as _sys
    _scripts = str(REPO / "scripts")
    if _scripts not in _sys.path:
        _sys.path.insert(0, _scripts)
    from alp_project import (  # type: ignore
        _CHIP_SUBSYSTEMS,
    )
    from alp_project_emit import (  # type: ignore
        _emit_library_hw_backends,
    )

    lines: list[str] = []
    lines.extend(_emit_baseline(slice_, diagnostics))
    lines.extend(_emit_console(diagnostics, slice_))
    lines.extend(_emit_som_caps(project, silicon, kconfig))

    chip_lines, chip_subsystems, resolved_chip_state = _emit_chips(
        project, _CHIP_SUBSYSTEMS)
    lines.extend(chip_lines)
    lines.extend(_emit_subsystems(slice_, chip_subsystems))

    iot_lines = _zephyr_iot_kconfig(project, slice_, resolved_chip_state)
    if iot_lines:
        lines.extend(iot_lines)

    lines.extend(_emit_libraries(project, slice_))
    # §D.lib.loader -- per-`libraries:` HW-accelerator backend wiring
    # (CONFIG_ALP_<LIB>_<BACKEND>=y). This is the single source both the
    # planner's build-plan `configArtefacts` and `alp_project.py --emit
    # zephyr-conf --core <id>` (the CMakeLists.txt-driven path) now share
    # -- folded in here (2026-07-20) so the two paths cannot silently
    # diverge on a `libraries:` entry with a hw_backends matcher; see
    # docs/adr/0020-sdk-owns-build-execution.md addendum.
    hw_backend_lines = _emit_library_hw_backends(slice_.libraries, project.sku)
    if hw_backend_lines:
        lines.append("# §D.lib.loader -- per-library HW-accelerator "
                     "wiring (auto-emitted).")
        lines.extend(hw_backend_lines)
        lines.append("")
    lines.extend(_emit_inference(project, slice_, silicon))
    lines.extend(_emit_memory(slice_))
    lines.extend(_emit_power(slice_))
    lines.extend(_emit_storage(project))
    lines.extend(_emit_ota(project))
    lines.extend(_emit_diagnostics(project))

    return "\n".join(lines) + "\n"


def _slice_local_conf(project: BoardProject, slice_: Slice) -> str:
    """Per-core local.conf snippet for a Yocto slice."""
    machine = slice_.machine or f"e1m-{project.sku.lower().replace('e1m-', '')}"
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/alp_orchestrate.py "
                 "-- append to local.conf.")
    lines.append(f"# Per-core slice `{slice_.core_id}` "
                 f"(image: {slice_.image or 'custom'})")
    # Console: a Yocto slice uses the Linux console (kernel console = the
    # SoM's debug UART via the `console=` kernel cmdline; userspace printf
    # goes to stdout/the controlling tty).  This is the Linux half of the
    # generic console auto-selection -- nothing to set in local.conf; the
    # BSP owns the `console=ttySC*` cmdline.  (Zephyr slices get the Alp
    # UART console instead; see _emit_zephyr_console.)
    console = _resolve_console((project.diagnostics or {}).get("console"),
                               slice_.os)
    if console == "linux":
        lines.append("# Console: Linux console (kernel `console=` cmdline "
                     "-> SoM debug UART; userspace -> stdout/tty).")
    lines.append(f'MACHINE = "{machine}"')
    if slice_.peripherals:
        joined = ", ".join(sorted(slice_.peripherals))
        lines.append("# Peripherals declared for this Yocto slice are "
                     f"BSP/kernel-owned ({joined}); no Zephyr Kconfig or "
                     "local.conf package knob is emitted here.")
    iot_lines = _yocto_iot_lines(project, slice_)
    if iot_lines:
        lines.extend(iot_lines)
    if slice_.libraries:
        imageinstall = " ".join(
            f"lib-{lib.replace('_', '-')}" for lib in slice_.libraries)
        lines.append(f'IMAGE_INSTALL:append = " {imageinstall}"')
    # Project-wide curated third-party libraries (top-level `libraries:`,
    # ADR 0018) with a Yocto integration section.  Guard keeps a project
    # with no such libraries byte-identical.
    library_pkgs = _library_layer.yocto_image_install(project, slice_)
    if library_pkgs:
        joined = " ".join(library_pkgs)
        lines.append(f'IMAGE_INSTALL:append = " {joined}"')
    if slice_.image:
        lines.append(f"# bitbake target: {slice_.image}")

    # Mender OTA wiring (board.yaml `ota:` block).  Emits Mender
    # `?=` (weak) assignments so hand-edited local.conf values in
    # the build dir still win.
    ota = project.ota or {}
    if ota.get("provider") == "mender":
        lines.append("")
        lines.append("# OTA (board.yaml `ota:` block)")
        lines.append('INHERIT += "mender-full"')
        if ota.get("artifact_name"):
            lines.append(f'MENDER_ARTIFACT_NAME ?= "{ota["artifact_name"]}"')
        srv = ota.get("server") or {}
        if srv.get("url"):
            lines.append(f'MENDER_SERVER_URL ?= "{srv["url"]}"')
        if srv.get("tenant"):
            lines.append(f'MENDER_TENANT_TOKEN ?= "{srv["tenant"]}"')
        sto = ota.get("storage") or {}
        if sto.get("device"):
            lines.append(f'MENDER_STORAGE_DEVICE_BASE ?= "{sto["device"]}"')
        if sto.get("boot_part_mb"):
            lines.append(f'MENDER_BOOT_PART_SIZE_MB ?= "{sto["boot_part_mb"]}"')
        if sto.get("total_size_mb"):
            lines.append(f'MENDER_STORAGE_TOTAL_SIZE_MB ?= "{sto["total_size_mb"]}"')
        if ota.get("poll_interval_s"):
            lines.append(f'MENDER_INVENTORY_INTERVAL ?= "{ota["poll_interval_s"]}"')

    return "\n".join(lines) + "\n"


def _slice_cmake_args(project: BoardProject, slice_: Slice) -> str:
    """Per-core cmake -D args for a baremetal / yocto slice.

    NPU-dispatch enables (DRP-AI, DEEPX) are driven from the SoM
    preset's `capabilities:` matrix -- never from board.yaml.  On
    multi-NPU SKUs (V2M101 = DRP-AI3 + DEEPX DX-M1) every available
    NPU is enabled so apps can dispatch concurrent independent models
    via alp_inference_open(.backend=...) per-handle.
    """
    family = project.som_preset.get("family") or "unknown"
    # resolve_capabilities merges SoC-JSON defaults with SoM overrides.
    capabilities = resolve_capabilities(project.som_preset, METADATA_ROOT)
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/alp_orchestrate.py "
                 "-- pass to cmake.")
    lines.append(f"-DALP_SOM_SKU={project.sku}")
    lines.append(f"-DALP_SOM_FAMILY={family}")
    # Per-SKU capability-restriction gate for <alp/soc_caps.h>: emitted
    # ONLY when the SoM preset declares `silicon_capabilities.unpopulated`,
    # so every unrestricted SKU's cmake-args output stays byte-identical.
    if som_unpopulated_capabilities(project.som_preset):
        lines.append(f"-DALP_SOM_{_som_define_slug(project.sku)}")
    lines.append(f"-DALP_CORE_ID={slice_.core_id}")
    # Cross-EVK board facade selector (<alp/board.h>).
    # Emitted only when the project resolves to a named board preset
    # (e.g. `preset: e1m-x-evk` -> board_name "E1M-X-EVK").
    # Inline boards with no preset/name skip this; the facade defaults
    # to an #error forcing the builder to set it explicitly (e.g. via
    # extra_args for native_sim testcases).
    if project.board_name:
        lines.append(f"-DALP_BOARD_{_board_define_slug(project.board_name)}")
    if slice_.toolchain:
        lines.append(f"-DALP_TOOLCHAIN={slice_.toolchain}")
    if capabilities.get("drp_ai"):
        # Must match the option name in src/yocto/CMakeLists.txt
        # (ALP_SDK_USE_DRPAI_V2N -- compiles inference_drpai.cpp).
        lines.append("-DALP_SDK_USE_DRPAI_V2N=ON")
    if capabilities.get("deepx_dxm1"):
        lines.append("-DALP_SDK_USE_DEEPX_DXM1=ON")
    # Project-wide curated third-party libraries (top-level `libraries:`,
    # ADR 0018) with a baremetal integration section.  Guard keeps a project
    # with no such libraries byte-identical.
    for arg in _library_layer.baremetal_cmake_args(project, slice_):
        lines.append(arg)
    return "\n".join(lines) + "\n"
