/*
 * Auto-generated by scripts/alp_orchestrate.py -- do not edit.
 * Regenerate after changes to board.yaml `ipc:` or the SoM's
 * memory_map / mailbox blocks.
 */

#ifndef ALP_SYSTEM_IPC_H
#define ALP_SYSTEM_IPC_H

#define ALP_IPC_SKU "E1M-V2N101"

/* rpmsg channel 'alp_default_rpmsg' -- endpoints a55_cluster, m33_sm */
#define ALP_IPC_ALP_DEFAULT_RPMSG_NAME       "alp_default_rpmsg"
#define ALP_IPC_ALP_DEFAULT_RPMSG_ADDR       0x00010000u
#define ALP_IPC_ALP_DEFAULT_RPMSG_SIZE       0x00080000u
#define ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT    0x000004e6u
#define ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT    0x000004e7u
#define ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH    0u

#endif /* ALP_SYSTEM_IPC_H */
