# SPDX-License-Identifier: Apache-2.0
"""Generate the canonical test fixtures: a minimal .alpmodel + its C byte
array, and the issue #1254 onnx_cpu regression fixture (tests/yocto/).

These three committed files (`tests/fixtures/alpmodel/minimal.alpmodel`,
`tests/unit/alpmodel_reader/src/fixture.h`, `tests/yocto/onnx_cpu_fixture.h`)
live in alp-sdk, not tan-cli -- `tests/unit/` and `tests/yocto/` are
Zephyr/Yocto C-test trees with no tan-cli equivalent (ADR-0028 Decision-3:
the on-device `.alpmodel` C reader, and the tests that exercise it, stay in
alp-sdk). `python/tests/model/test_package.py` compares the (now relocated)
Python encoder's output against these files read out of a bound alp-sdk
checkout, the same way `tests.conftest.sdk_root()` binds every other
cross-repo test in this suite.

Run as: python -m tan.model._gen_fixture --root <path-to-alp-sdk-checkout>
        (or set ALP_SDK_ROOT; --root wins when both are given)"""
from __future__ import annotations
import argparse
import os
import sys
from pathlib import Path
from .manifest import Manifest, Tensor, Target, Coverage
from .package import write_package

_SDK_MARKER = ("scripts", "alp_project.py")


def _manifest() -> Manifest:
    return Manifest(
        name="minimal",
        src_sha=bytes(range(32)),
        inputs=[Tensor("int8", 4, [1, 96, 96, 1], 0.0078, -1)],
        outputs=[Tensor("int8", 2, [1, 2], 0.004, 0)],
        targets=[
            Target("ethos_u", "alif:ensemble:e8", "vela_tflite", "ethos-u85-256",
                   65536, {"sram_kib": 256, "op_features": []}, 0, compiler_version="vela 4.1.0"),
            Target("cpu", "*", "tflite", "", 131072,
                   {"sram_kib": 0, "op_features": []}, 1, compiler_version="passthrough"),
        ],
        coverage=[Coverage("deepx_dxm1", "", "skipped", "dx-compiler not found")],
    )


def build_fixture_bytes() -> bytes:
    return write_package(_manifest(), [b"VELA\x00\x01\x02\x03", b"TFLITE\x00"])


def _onnx_cpu_manifest() -> Manifest:
    return Manifest(
        name="onnx_cpu_smoke",
        src_sha=bytes(range(32)),
        targets=[
            Target("cpu", "*", "onnx", "", 65536, {"sram_kib": 0, "op_features": []}, 0,
                   compiler_version="passthrough"),
        ],
    )


def build_onnx_cpu_fixture_bytes() -> bytes:
    """Issue #1254 end-to-end regression fixture (tests/yocto/alpmodel_onnx_cpu.c):
    an "onnx" blob_format .alpmodel container, decoded by the real
    zcbor-backed alp_model_parse()."""
    return write_package(_onnx_cpu_manifest(), [b"\x08\x01\x12\x04test-onnx-blob-placeholder"])


def to_c_header(raw: bytes, *, array_name: str = "alp_model_fixture",
                 guard: str = "ALP_MODEL_FIXTURE_H") -> str:
    # clang-format guards: the array wrap width is the generator's,
    # not the formatter's -- without them a repo-wide clang-format
    # sweep rewraps the rows and the committed-matches-generator
    # pytest fails.
    lines = ["/* GENERATED by `python -m tan.model._gen_fixture` -- do not edit. */",
             "/* clang-format off */",
             f"#ifndef {guard}", f"#define {guard}",
             "#include <stddef.h>", "#include <stdint.h>", "",
             f"static const uint8_t {array_name}[] = {{"]
    for i in range(0, len(raw), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in raw[i:i + 12])
        lines.append(f"    {chunk},")
    lines += ["};",
              f"static const size_t {array_name}_len = {len(raw)};",
              "", f"#endif /* {guard} */",
              "/* clang-format on */", ""]
    return "\n".join(lines)


def _resolve_sdk_root(explicit: str | None) -> Path:
    """`--root` wins over `ALP_SDK_ROOT`; either must name a real alp-sdk
    checkout (the same `scripts/alp_project.py` marker `tan`'s own SDK
    discovery uses), not just an existing directory -- a typo'd path should
    fail loudly here, not by writing into the wrong tree."""
    root = explicit or os.environ.get("ALP_SDK_ROOT")
    if not root:
        print("tan.model._gen_fixture: no alp-sdk checkout given -- pass "
              "--root <path> or set ALP_SDK_ROOT.", file=sys.stderr)
        raise SystemExit(1)
    resolved = Path(root).resolve()
    if not resolved.joinpath(*_SDK_MARKER).is_file():
        print(f"tan.model._gen_fixture: {resolved} does not look like an "
              f"alp-sdk checkout (missing {'/'.join(_SDK_MARKER)}).",
              file=sys.stderr)
        raise SystemExit(1)
    return resolved


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="alp-sdk checkout to write the fixtures into "
                                        "(defaults to $ALP_SDK_ROOT)")
    args = parser.parse_args(argv)
    sdk_root = _resolve_sdk_root(args.root)

    alpmodel = sdk_root / "tests/fixtures/alpmodel/minimal.alpmodel"
    header = sdk_root / "tests/unit/alpmodel_reader/src/fixture.h"
    onnx_cpu_header_path = sdk_root / "tests/yocto/onnx_cpu_fixture.h"

    raw = build_fixture_bytes()
    alpmodel.parent.mkdir(parents=True, exist_ok=True)
    header.parent.mkdir(parents=True, exist_ok=True)
    alpmodel.write_bytes(raw)
    header.write_text(to_c_header(raw), encoding="utf-8", newline="")

    onnx_cpu_raw = build_onnx_cpu_fixture_bytes()
    onnx_cpu_header = to_c_header(onnx_cpu_raw, array_name="k_onnx_cpu_alpmodel",
                                   guard="ALP_MODEL_ONNX_CPU_FIXTURE_H")
    onnx_cpu_header_path.parent.mkdir(parents=True, exist_ok=True)
    onnx_cpu_header_path.write_text(onnx_cpu_header, encoding="utf-8", newline="")

    print(f"wrote {alpmodel} ({len(raw)} bytes), {header} and {onnx_cpu_header_path}")


if __name__ == "__main__":
    main()
