# SPDX-License-Identifier: Apache-2.0
"""Generate the canonical test fixtures: a minimal .alpmodel + its C byte
array, and the issue #1254 onnx_cpu regression fixture (tests/yocto/).
Run as: python -m alp_model._gen_fixture   (writes all committed files)."""
from __future__ import annotations
from pathlib import Path
from .manifest import Manifest, Tensor, Target, Coverage
from .package import write_package

_ROOT = Path(__file__).resolve().parents[2]
_ALPMODEL = _ROOT / "tests/fixtures/alpmodel/minimal.alpmodel"
_HEADER = _ROOT / "tests/unit/alpmodel_reader/src/fixture.h"
_ONNX_CPU_HEADER = _ROOT / "tests/yocto/onnx_cpu_fixture.h"


def _manifest() -> Manifest:
    return Manifest(
        name="minimal",
        src_sha=bytes(range(32)),
        inputs=[Tensor("int8", 4, [1, 96, 96, 1], 0.0078, -1)],
        outputs=[Tensor("int8", 2, [1, 2], 0.004, 0)],
        targets=[
            Target("ethos_u", "alif:ensemble:e8", "vela_tflite", "ethos-u85-256",
                   65536, {"sram_kib": 256, "op_features": []}, 0, compiler_version="vela 4.1.0"),
            Target("cpu", "*", "tflite", "", 131072,
                   {"sram_kib": 0, "op_features": []}, 1, compiler_version="passthrough"),
        ],
        coverage=[Coverage("deepx_dxm1", "", "skipped", "dx-compiler not found")],
    )


def build_fixture_bytes() -> bytes:
    return write_package(_manifest(), [b"VELA\x00\x01\x02\x03", b"TFLITE\x00"])


def _onnx_cpu_manifest() -> Manifest:
    return Manifest(
        name="onnx_cpu_smoke",
        src_sha=bytes(range(32)),
        targets=[
            Target("cpu", "*", "onnx", "", 65536, {"sram_kib": 0, "op_features": []}, 0,
                   compiler_version="passthrough"),
        ],
    )


def build_onnx_cpu_fixture_bytes() -> bytes:
    """Issue #1254 end-to-end regression fixture (tests/yocto/alpmodel_onnx_cpu.c):
    an "onnx" blob_format .alpmodel container, decoded by the real
    zcbor-backed alp_model_parse()."""
    return write_package(_onnx_cpu_manifest(), [b"\x08\x01\x12\x04test-onnx-blob-placeholder"])


def to_c_header(raw: bytes, *, array_name: str = "alp_model_fixture",
                 guard: str = "ALP_MODEL_FIXTURE_H") -> str:
    # clang-format guards: the array wrap width is the generator's,
    # not the formatter's -- without them a repo-wide clang-format
    # sweep rewraps the rows and the committed-matches-generator
    # pytest fails.
    lines = ["/* GENERATED by `python -m alp_model._gen_fixture` -- do not edit. */",
             "/* clang-format off */",
             f"#ifndef {guard}", f"#define {guard}",
             "#include <stddef.h>", "#include <stdint.h>", "",
             f"static const uint8_t {array_name}[] = {{"]
    for i in range(0, len(raw), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in raw[i:i + 12])
        lines.append(f"    {chunk},")
    lines += ["};",
              f"static const size_t {array_name}_len = {len(raw)};",
              "", f"#endif /* {guard} */",
              "/* clang-format on */", ""]
    return "\n".join(lines)


def main() -> None:
    raw = build_fixture_bytes()
    _ALPMODEL.parent.mkdir(parents=True, exist_ok=True)
    _HEADER.parent.mkdir(parents=True, exist_ok=True)
    _ALPMODEL.write_bytes(raw)
    _HEADER.write_text(to_c_header(raw), encoding="utf-8", newline="")

    onnx_cpu_raw = build_onnx_cpu_fixture_bytes()
    onnx_cpu_header = to_c_header(onnx_cpu_raw, array_name="k_onnx_cpu_alpmodel",
                                   guard="ALP_MODEL_ONNX_CPU_FIXTURE_H")
    _ONNX_CPU_HEADER.parent.mkdir(parents=True, exist_ok=True)
    _ONNX_CPU_HEADER.write_text(onnx_cpu_header, encoding="utf-8", newline="")

    print(f"wrote {_ALPMODEL} ({len(raw)} bytes), {_HEADER} and {_ONNX_CPU_HEADER}")


if __name__ == "__main__":
    main()
