# SPDX-License-Identifier: Apache-2.0
"""Per-example facets (`category`, `som`, `board`, `cores`, `coreCount`,
`osSet`, `declares`) read out of alp-sdk's generated `metadata/catalog.json`.

tan-cli#484: `tan examples` used to publish only
`id`/`sourceDir`/`title`/`description`, so no consumer could filter the
catalogue by core count, OS, or SoM -- not even by category, though
`examples/` has always been grouped into one. alp-sdk's companion issue
answered this by deriving exactly these facets through its topology resolver
(`scripts/gen_catalog.py::_resolved_core_facets`, which calls the SAME
`alp_project.py --emit os-topology` path `tan build` itself plans a project
against) and publishing them pre-computed in `metadata/catalog.json`
(`build_examples()`). Measured against alp-sdk `origin/dev`
(`20baaaf19`): the facets are already there.

**tan reads that generated JSON; it does not resolve topology itself.**
I-26 keeps `metadata/**` hardware-fact resolution in alp-sdk -- this module
is the `examples` analogue of `tan.core.error_catalog` reading
`metadata/error-catalog.json` rather than re-deriving diagnostics, and of
`tan.core.example_catalog` reading `metadata/templates/catalog-v1.json`
rather than re-resolving SoM support. A facet this module cannot find in the
catalogue is left OFF the entry, never guessed: `cores`/`coreCount`/`osSet`
resolve through topology and reproducing that logic here would be exactly
the drift ADR-0020 exists to prevent.

**Degrades silently, never refuses `tan examples`.** A checkout predating
`catalog.json`, or one where it fails to parse, still lists every example by
directory discovery exactly as before -- the catalogue is enrichment, not a
second source of truth for WHICH examples exist. Mirrors
`tan.core.example_catalog.unsupported_som`'s own "never raises, absence
means nothing to report" contract for the neighbouring
`templates/catalog-v1.json` reader.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

#: `<sdk_root>/metadata/catalog.json`, generated by `scripts/gen_catalog.py`.
CATALOG_RELATIVE = Path("metadata") / "catalog.json"


@dataclass(frozen=True)
class ExampleFacets:
    """One example's catalogue-derived facets. `category` is always known --
    it is the catalogue's own grouping key, mirrored from the example's
    parent directory -- every other field is optional, exactly as
    `gen_catalog.py` leaves it: a key it has nothing to say for is omitted
    from the source document entirely rather than emitted null or empty
    (no `som:` on a portable example; `cores`/`coreCount`/`osSet` all
    absent together when the board's topology did not resolve, e.g.
    `SdkRevisionNotBuildable`)."""

    category: str
    som: str | None
    board: str | None
    cores: tuple[dict, ...] | None
    core_count: int | None
    os_set: tuple[str, ...] | None
    declares: dict[str, bool] | None


def load_example_facets(sdk_root: Path) -> dict[str, ExampleFacets]:
    """`{sourceDir: ExampleFacets}` for every example the bound checkout's
    catalogue knows about, or `{}` when there is nothing usable to read.

    Never raises: a missing file (older SDK), an unreadable one, invalid
    JSON, or a document that is not shaped the way `gen_catalog.py` writes
    it all collapse to "no facets this run" -- the caller already has a
    complete example list from directory discovery and must not lose any of
    it because the enrichment source is stale, absent, or malformed.
    """
    path = sdk_root / CATALOG_RELATIVE
    try:
        raw = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}
    try:
        doc = json.loads(raw)
    except ValueError:
        return {}
    if not isinstance(doc, dict):
        return {}
    by_category = doc.get("examples")
    if not isinstance(by_category, dict):
        return {}

    facets: dict[str, ExampleFacets] = {}
    for category, entries in by_category.items():
        if not isinstance(category, str) or not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            name = entry.get("name")
            if not isinstance(name, str) or not name:
                continue
            # `discover_examples`' own `source_dir` shape (`_subdirectories`
            # walk), always `/`-joined -- this is the join key the two sides
            # meet on, not `entry["path"]` (which additionally carries the
            # `examples/` prefix `gen_catalog.py` writes it with).
            facets[f"{category}/{name}"] = _facets_from_entry(category, entry)
    return facets


def _facets_from_entry(category: str, entry: dict) -> ExampleFacets:
    som = entry.get("som")
    board = entry.get("board")
    cores = entry.get("cores")
    core_count = entry.get("coreCount")
    os_set = entry.get("osSet")
    declares = entry.get("declares")
    return ExampleFacets(
        category=category,
        som=som if isinstance(som, str) else None,
        board=board if isinstance(board, str) else None,
        cores=tuple(cores) if isinstance(cores, list) else None,
        core_count=core_count if isinstance(core_count, int) else None,
        os_set=tuple(os_set) if isinstance(os_set, list) else None,
        declares=declares if isinstance(declares, dict) else None,
    )
