# SPDX-License-Identifier: Apache-2.0
"""tan-cli#437: the release build resolves from a LOCK, and this proves it.

`release.yml`'s `build` job and `clean-host.yml`'s `freeze-and-smoke` job used
to run `pip install ".[monitor]" "pyinstaller>=6.10"` against a live PyPI
resolution -- no lock, no hashes, an unbounded `pyinstaller` floor. Re-running
the same immutable tag on a later day could resolve a different
typer/click/rich/pyyaml/jsonschema/truststore/certifi/pyinstaller and ship
different bytes under an identical version string.

`python/release-requirements.lock.txt` (regenerated by
`scripts/generate_release_lock.py`, a real `uv pip compile --universal
--generate-hashes` run -- see that script's docstring) is the fix; both
workflows now run `pip install --require-hashes -r` it. But a lockfile
nothing checks is the same defect wearing a hat: this module is what keeps
the committed lock actually covering what `pyproject.toml` currently declares,
without needing network access or `uv` installed to run (this suite's own
`python -m pytest tests -q` gate has neither) -- it is a STATIC, structural
check over the two committed files, not a re-resolution.

Two failure directions matter, matching `test_declared_dependencies.py`'s own
shape:
  * a runtime distribution pyproject.toml declares that the lock does not
    pin+hash at all (drift the other direction from the click incident --
    here the lock is what could silently fall behind);
  * a lock entry with no hash, or a version outside pyproject's own declared
    range -- either one means `pip install --require-hashes` either cannot
    enforce anything for that package, or is enforcing a version nobody
    running `--check` today would have chosen.
"""

from __future__ import annotations

import pathlib
import re
import tomllib

_HERE = pathlib.Path(__file__).resolve()
PYTHON_DIR = _HERE.parents[2]
PYPROJECT = PYTHON_DIR / "pyproject.toml"
LOCK = PYTHON_DIR / "release-requirements.lock.txt"

_HASH_RE = re.compile(r"--hash=sha256:[0-9a-fA-F]{64}")
_ENTRY_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)")


def _norm(name: str) -> str:
    return name.strip().lower().replace("_", "-")


def _declared_runtime_distributions() -> dict[str, str]:
    """{normalised name: raw specifier} for base deps + the `monitor` extra.

    `monitor` specifically: a frozen binary bundles it at build time (see
    `build_binary.sh`'s header -- `tan monitor` is a command the binary
    advertises and a customer can never add an extra after the fact), so the
    release lock has to cover it even though a plain `pip install alp-tan`
    does not.
    """
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    project = data["project"]
    out: dict[str, str] = {}
    for spec in project["dependencies"]:
        out[_norm(re.split(r"[<>=!~\[; ]", spec, maxsplit=1)[0])] = spec
    for spec in project["optional-dependencies"]["monitor"]:
        out[_norm(re.split(r"[<>=!~\[; ]", spec, maxsplit=1)[0])] = spec
    return out


def _parse_release(text: str) -> str | None:
    """release segment of a PEP 440-ish `X.Y[.Z...]` string, digits-only."""
    m = re.match(r"\d+(?:\.\d+)*", text)
    return m.group(0) if m else None


def _release_tuple(text: str) -> tuple[int, ...]:
    rel = _parse_release(text)
    assert rel is not None, f"not a version-shaped string: {text!r}"
    return tuple(int(p) for p in rel.split("."))


def _satisfies(version: str, specifier: str) -> bool:
    """Minimal `>=`, `<=`, `>`, `<`, `==`, `!=`, comma-AND evaluator.

    Deliberately not a full PEP 440 implementation (pre-release ordering,
    local versions, etc.) -- pyproject.toml's own dependency specifiers here
    are all plain release-segment comparisons (`>=0.26,<0.28`, `>=13`, ...),
    and this gate has no `packaging` dependency to reach for (it is not a
    declared runtime or dev dependency, and this suite's own gate command
    installs neither). Good enough for what is actually written today; if a
    future specifier needs real pre-release semantics, that is the moment to
    add `packaging` as a real dependency instead of growing this parser.
    """
    v = _release_tuple(version)
    for clause in specifier.split(","):
        clause = clause.strip()
        for op, cmp_ in (
            (">=", lambda a, b: a >= b),
            ("<=", lambda a, b: a <= b),
            ("==", lambda a, b: a == b),
            ("!=", lambda a, b: a != b),
            (">", lambda a, b: a > b),
            ("<", lambda a, b: a < b),
        ):
            if clause.startswith(op):
                bound = _release_tuple(clause[len(op) :])
                if not cmp_(v, bound):
                    return False
                break
    return True


def _lock_entries() -> dict[str, tuple[str, int]]:
    """{normalised name: (version, hash_count)} pinned in the lock file."""
    assert LOCK.exists(), f"{LOCK} does not exist -- run generate_release_lock.py"
    entries: dict[str, tuple[str, int]] = {}
    name = None
    version = None
    hashes = 0
    for line in LOCK.read_text(encoding="utf-8").splitlines():
        m = _ENTRY_RE.match(line)
        if m:
            if name is not None:
                entries[name] = (version, hashes)
            name, version = _norm(m.group(1)), m.group(2)
            hashes = len(_HASH_RE.findall(line))
            continue
        if name is not None:
            hashes += len(_HASH_RE.findall(line))
            # A blank line or the next unindented comment/entry ends this
            # record's continuation lines -- the ` # via` annotation lines
            # are indented too, so they do not end it, and carry no hashes
            # to double-count anyway.
    if name is not None:
        entries[name] = (version, hashes)
    return entries


def test_the_lock_file_parses_into_more_than_a_handful_of_entries():
    """Guard against a vacuous pass: an empty or truncated lock still
    'contains' every required name vacuously if the loop below never runs."""
    entries = _lock_entries()
    assert len(entries) >= 15, (
        f"only {len(entries)} entries parsed out of {LOCK} -- either the lock "
        f"is badly truncated or this parser stopped reading it correctly"
    )


def test_every_declared_runtime_dependency_is_pinned_and_hashed_in_the_lock():
    required = _declared_runtime_distributions()
    entries = _lock_entries()
    missing: list[str] = []
    unhashed: list[str] = []
    out_of_range: list[str] = []
    for dist, specifier in sorted(required.items()):
        if dist not in entries:
            missing.append(f"{dist} (pyproject: `{specifier}`)")
            continue
        version, hash_count = entries[dist]
        if hash_count < 1:
            unhashed.append(f"{dist}=={version}")
        if not _satisfies(version, specifier):
            out_of_range.append(
                f"{dist}=={version} does not satisfy pyproject's `{specifier}`"
            )
    assert not missing, (
        "pyproject.toml declares a runtime (or `monitor`-extra) dependency "
        "with no matching pinned+hashed entry in "
        f"{LOCK.name}. A release build installing `--require-hashes -r "
        f"{LOCK.name}` plus `--no-deps .` would fail to satisfy it (or, worse, "
        "resolve it unpinned some other way). Run "
        "`python python/scripts/generate_release_lock.py` and commit the "
        "result:\n  " + "\n  ".join(missing)
    )
    assert not unhashed, (
        f"{LOCK.name} pins a required distribution with NO hash. "
        "`pip install --require-hashes` refuses to install ANY requirement "
        "unhashed once hash-checking mode is on for the file, so this is not "
        "a partial gap -- it breaks the whole install:\n  " + "\n  ".join(unhashed)
    )
    assert not out_of_range, (
        f"{LOCK.name} pins a version outside pyproject.toml's own declared "
        "range for that distribution -- the lock and the floor/ceiling "
        "pyproject documents (with its own reasoning, see that file's "
        "comments) have drifted apart:\n  " + "\n  ".join(out_of_range)
    )


def test_pyinstaller_is_pinned_and_hashed_at_or_above_its_declared_floor():
    """`pyinstaller` (and `setuptools`, its build-isolation floor) are
    deliberately NOT in pyproject.toml's `dependencies` -- see
    `build_binary.sh`'s header, "PyInstaller is a BUILD-TIME tool only" -- so
    the check above never sees them. They still have to be pinned+hashed in
    the release lock; this is the release.yml/clean-host.yml counterpart to
    the check above, over the build-time-only additions declared in
    `scripts/release-lock-build-time-extras.in`.
    """
    entries = _lock_entries()
    extras_in = PYTHON_DIR / "scripts" / "release-lock-build-time-extras.in"
    assert extras_in.exists(), f"{extras_in} is missing"
    for line in extras_in.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        dist = _norm(re.split(r"[<>=!~\[; ]", line, maxsplit=1)[0])
        specifier = line[len(dist) :].lstrip()
        assert dist in entries, (
            f"build-time tool `{dist}` (declared in {extras_in.name}) has no "
            f"pinned entry in {LOCK.name}"
        )
        version, hash_count = entries[dist]
        assert hash_count >= 1, f"{dist}=={version} in {LOCK.name} has no hash"
        if specifier:
            assert _satisfies(version, specifier), (
                f"{dist}=={version} in {LOCK.name} does not satisfy "
                f"`{specifier}` from {extras_in.name}"
            )


def test_satisfies_helper_actually_discriminates():
    """Guard against `_satisfies` degrading into `return True` -- prove it
    rejects a real out-of-range case in both directions before trusting it
    above."""
    assert _satisfies("0.27.2", ">=0.26,<0.28")
    assert not _satisfies("0.30.0", ">=0.26,<0.28")
    assert not _satisfies("0.10.0", ">=0.26,<0.28")
    assert _satisfies("13.4.0", ">=13")
    assert not _satisfies("12.9.0", ">=13")
