# SPDX-License-Identifier: Apache-2.0
"""native_sim board overlay emission (`--emit native-sim-overlay`).

RELOCATED (was alp-sdk `scripts/alp_project_emit/native_sim.py`) -- see this
package's `__init__.py` for the move's contract.

One change beyond the import repoint: the three form-factor STRINGS are derived
from `_sku_form_factor`'s own return value instead of written out per branch.
alp-sdk spelled `form_factor = "E1M-X"` literally, which inside `tan` is a
hardware fact and fails `tests/gates/test_no_new_hardware_facts.py` -- correctly,
since naming the connector family is metadata's job, not tan's. `e1m-x` ->
`E1M-X` / `e1m_x_pinout.h` / `ALP_E1M_X_GPIO` is a pure re-spelling of the token
the loader already resolved, so the emitted bytes do not move;
`test_the_in_process_engine_matches_alp_project_for_every_mode` proves that over
every `board.yaml` in the SDK's `examples/`.
"""

from __future__ import annotations

from typing import Any

from ..project_loader import _sku_form_factor

from . import _e1m_gpio_canonical, _e1m_x_gpio_canonical


# ---------------------------------------------------------------------
# native_sim overlay emission (canonical alp,pin-array on gpio-emul)
# ---------------------------------------------------------------------
#
# Studio + `alp init` want a native_sim board overlay so a scaffolded GPIO
# app links + runs on `native_sim/native/64` (host emulation, emulated CI)
# with no silicon.  Unlike `--emit dts-overlay` -- which stubs every
# pin-array triplet at <&gpio0 0> pending the upstream SoM board file --
# gpio-emul IS the backing controller under native_sim, so this overlay is
# complete and directly buildable.  Keeping it here (not hand-rolled in a
# downstream scaffolder) means the E1M/E1M-X pad ABI lives in exactly one
# place: the canonical helpers above.

# zephyr,gpio-emul controllers cap at 32 pins.
_GPIO_EMUL_MAX_PINS = 32


def _emit_native_sim_overlay(project: dict[str, Any]) -> str:
    """Emit a native_sim board overlay: the canonical alp,pin-array mapped
    onto zephyr,gpio-emul controllers.

    The pin-array is the full positional map in the form-factor pinout header's
    canonical order, so alp_z_gpio_resolve(pin_id) is a direct index for
    any pad (the GPIO backend derives ALP_PIN_COUNT from this node's gpios
    length).  gpio-emul caps at 32 pins, so the pads span as many
    controllers as the active form factor needs.  Every pad defaults to
    GPIO_ACTIVE_HIGH; an app that needs a
    different polarity (e.g. an active-low button) overrides its own pad.

    GPIO only: non-GPIO peripherals (display, sensors) have no universal
    native_sim emulation, so an app that needs them adds its own emulated
    nodes (e.g. a zephyr,dummy-dc display), exactly as the curated examples
    do.
    """
    sku = project["som"]["sku"]
    # `e1m-x` / `e1m` -> the three spellings the overlay's prose uses. Derived,
    # not written out: the connector-family name is a hardware fact (I-26).
    ff = _sku_form_factor(sku)
    form_factor = ff.upper()
    pinout_header = f"{ff.replace('-', '_')}_pinout.h"
    gpio_macro_prefix = f"ALP_{form_factor.replace('-', '_')}_GPIO"
    if ff == "e1m-x":
        canonical = _e1m_x_gpio_canonical()
        index_summary = [
            "         *   0..35  IO0..IO35       36..43 PWM0..PWM7",
            "         *   44..51 ENC0_X..ENC3_Y  52..59 ADC0..ADC7   60..61 DAC0..DAC1",
            "         *   62..72 I2C2/3 + SPI2 + CAN1",
            "         *   73..98 LCD_B0..LCD_B23 + LCD_HSYNC/LCD_VSYNC */",
        ]
    else:
        canonical = _e1m_gpio_canonical()
        index_summary = [
            "         *   0..25  IO0..IO25       26..33 PWM0..PWM7",
            "         *   34..41 ENC0_X..ENC3_Y  42..49 ADC0..ADC7   50..51 DAC0..DAC1 */",
        ]
    n = len(canonical)
    n_ctrl = (n + _GPIO_EMUL_MAX_PINS - 1) // _GPIO_EMUL_MAX_PINS

    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Auto-generated by scripts/alp_project.py "
                 "--emit native-sim-overlay -- do not edit by hand.")
    lines.append(f" * Regenerate after changes to the {pinout_header} GPIO order.")
    lines.append(" *")
    lines.append(f" * native_sim GPIO emulation for SoM SKU {sku}: the canonical")
    lines.append(" * alp,pin-array mapped onto zephyr,gpio-emul so alp_gpio_open(pin_id)")
    lines.append(f" * resolves under `west build -b native_sim/native/64`.  All {n} {form_factor} pads")
    lines.append(" * are present so any pin_id resolves; pads default to GPIO_ACTIVE_HIGH")
    lines.append(" * -- override per pad in your app for a different polarity.  GPIO only:")
    lines.append(" * add your own emulated nodes for non-GPIO peripherals (display, etc.).")
    lines.append(" */")
    lines.append("")
    lines.append("#include <zephyr/dt-bindings/gpio/gpio.h>")
    lines.append("")
    lines.append("/ {")

    # gpio-emul controllers -- one per 32-pad span.
    for c in range(n_ctrl):
        base = c * _GPIO_EMUL_MAX_PINS
        count = min(_GPIO_EMUL_MAX_PINS, n - base)
        lines.append(f"    gpio_emul{c}: gpio_emul{c} {{")
        lines.append('        compatible = "zephyr,gpio-emul";')
        lines.append('        status = "okay";')
        lines.append("        gpio-controller;")
        lines.append("        rising-edge;")
        lines.append("        falling-edge;")
        lines.append("        #gpio-cells = <2>;")
        lines.append(f"        ngpios = <{count}>;")
        lines.append("    };")
        lines.append("")

    # alp,pin-array -- the full positional map spanning the controllers.
    lines.append("    alp_pins: alp-pins {")
    lines.append('        compatible = "alp,pin-array";')
    lines.append(f"        /* {n} entries in {form_factor} canonical order ({pinout_header}).  Indices:")
    for line in index_summary:
        lines.append(line)
    lines.append("        gpios =")
    for i, suffix in enumerate(canonical):
        ctrl = i // _GPIO_EMUL_MAX_PINS
        local = i % _GPIO_EMUL_MAX_PINS
        terminator = ";" if i == n - 1 else ","
        lines.append(
            f"            <&gpio_emul{ctrl} {local:2d} GPIO_ACTIVE_HIGH>{terminator}"
            f"  /* [{i:2d}] {gpio_macro_prefix}_{suffix} */"
        )
    lines.append("    };")
    lines.append("};")

    return "\n".join(lines) + "\n"
