/*
 * Auto-generated by scripts/alp_orchestrate.py -- do not edit.
 * Regenerate after changes to board.yaml `ipc:` or the SoM's
 * memory_map / mailbox blocks.
 */

#ifndef ALP_SYSTEM_IPC_H
#define ALP_SYSTEM_IPC_H

#define ALP_IPC_SKU "E1M-AEN801"

/* raw_shmem channel 'alp_shmem0' -- endpoints m55_hp, m55_he */
/* BLOCKED: ipc entry 'alp_shmem0' endpoints ['m55_hp', 'm55_he'] only match memory_map region(s) in SoM E1M-AEN801 that are ineligible for an IPC carve-out: 'mcuboot' (region 'mcuboot' [0x80000000, 0x80010000) is flash-class (contained in the SoC's declared on-die MRAM aperture) -- not safe as an IPC carve-out target); 'reserved' (region 'reserved' [0x80550000, 0x80560000) is flash-class (contained in the SoC's declared on-die MRAM aperture) -- not safe as an IPC carve-out target); 'storage' (region 'storage' [0x80560000, 0x80578000) is flash-class (contained in the SoC's declared on-die MRAM aperture) -- not safe as an IPC carve-out target); 'atoc' (region 'atoc' [0x80578000, 0x80580000) is flash-class (contained in the SoC's declared on-die MRAM aperture) -- not safe as an IPC carve-out target); 'mram_main' (region 'mram_main' has an unresolved base ('TBD') so containment against the declared MRAM aperture can't be verified, and its authored write_authority is 'composite', not 'customer_runtime').  Add a region whose resolved base sits outside the SoC's declared MRAM aperture (or, if inside it, one that resolves `write_authority: customer_runtime`) to metadata/e1m_modules/E1M-AEN801.yaml, or remove the matching ipc entry from board.yaml. */
/* IPC channel 'alp_shmem0' is blocked; fix the SoM metadata before depending on this channel at runtime. */
#define ALP_IPC_ALP_SHMEM0_NAME       "alp_shmem0"
#define ALP_IPC_ALP_SHMEM0_ADDR       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_SIZE       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_SRC_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_DST_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_MBOX_CH    0u    /* stub: blocked */

#endif /* ALP_SYSTEM_IPC_H */
