/*
 * Auto-generated by scripts/alp_orchestrate.py -- do not edit.
 * Regenerate after changes to board.yaml `ipc:` or the SoM's
 * memory_map / mailbox blocks.
 */

#ifndef ALP_SYSTEM_IPC_H
#define ALP_SYSTEM_IPC_H

#define ALP_IPC_SKU "E1M-AEN801"

/* raw_shmem channel 'alp_shmem0' -- endpoints m55_hp, m55_he */
/* BLOCKED: memory_map.base is TBD for region 'mram_main' in SoM E1M-AEN801; this SoM hasn't been HW-mapped yet so IPC carve-outs cannot be allocated.  Add a `memory_map:` block to metadata/e1m_modules/E1M-AEN801.yaml (or per-region `base`) or remove the matching ipc entry from board.yaml. */
/* IPC channel 'alp_shmem0' is blocked; fix the SoM metadata before depending on this channel at runtime. */
#define ALP_IPC_ALP_SHMEM0_NAME       "alp_shmem0"
#define ALP_IPC_ALP_SHMEM0_ADDR       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_SIZE       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_SRC_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_DST_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_SHMEM0_MBOX_CH    0u    /* stub: blocked */

#endif /* ALP_SYSTEM_IPC_H */
