# SPDX-License-Identifier: Apache-2.0
"""Shared scaffolding for `tests/planner/`'s three `os: baremetal` coverage
modules (tan-cli#1036 / tan-cli#1042):

  * `test_baremetal_slice_post_commands_coverage.py`
  * `test_baremetal_command_and_flash_coverage.py`
  * `test_baremetal_plan_emit_coverage.py`

It owns the SDK-root binding dance those three share -- `bind_planner_sdk_root`
and the autouse `bound_sdk_root` fixture that calls it -- plus the synthetic
`BoardProject`/`Slice` pair and the two small helpers the last two use to
reach the baremetal arms with NO alp-sdk checkout, no `board.yaml` and no
`metadata/**` tree.

THE BINDER LIVES HERE AND ONLY HERE, and that is the point of the module
rather than a tidiness preference. It took three review rounds on tan-cli#1044
to get right (see `bind_planner_sdk_root`), and a fourth round that reaches
one copy and not another would silently reintroduce the failure the first
three fixed: a stale copy reuses the non-SDK stub
`tests/core/test_flow_d_manifest_fields.py::_bind_stub_sdk_root` leaves bound,
imports the real `tan.planner` under it, freezes `paths.REPO` there for the
rest of the process, and every later `bind_sdk_root(<real SDK>)` raises.
That is now gated, by name:
`tests/gates/test_shared_test_helpers_have_one_definition.py` seeds its
allow-list with `bind_planner_sdk_root` and fails if a second module-level
definition of it (in either spelling) appears anywhere under `python/tests/**`
(tan-cli#1081). Until then nothing did -- the older
`tests/gates/test_shared_helpers_have_one_definition.py` scopes its walk to
`python/tan/**` and still never looks at `tests/`.

Nothing in this module may import `tan.planner` (or any submodule of it) at
module scope: `tan/planner/paths.py` evaluates `REPO = sdk_root()` at ITS OWN
import time and raises when no root is bound yet. Every planner import here
and in the three consumers is therefore deliberately made INSIDE a function,
after `bind_planner_sdk_root` has run.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Optional

import pytest

from tan import planner_root
from tests.conftest import sdk_root as _real_sdk_root

# Captured at COLLECTION time (module import), before `tests/conftest.py`'s
# per-test, autouse `_scrub_sdk_discovery_env` fixture deletes `ALP_SDK_ROOT`
# from the process environment -- `sdk_root()`'s own docstring requires the
# module-level call for exactly this reason.
SDK = _real_sdk_root()

#: The full `alp-baremetal.cmake` text `_baremetal_project_include` renders,
#: minus its final `add_compile_definitions(...)` line -- the only part that
#: varies with the slice. Split out so each test that asserts the file's
#: contents pins the WHOLE file byte-for-byte without restating five lines of
#: banner, and so the two modules that assert it cannot drift apart.
PROJECT_INCLUDE_PREAMBLE = (
    "# Auto-generated by scripts/alp_orchestrate -- do not edit.\n"
    "# Pulled in by the slice's configure via -DCMAKE_PROJECT_INCLUDE.\n"
    "# Compile-time guards <alp/board.h> / <alp/soc_caps.h> test with\n"
    "# #if defined(...); a CMake cache variable would not reach the\n"
    "# preprocessor at all.\n"
)


def bind_planner_sdk_root(tmp_path: Path) -> None:
    """Bind the planner's SDK root, preferring the REAL bound checkout.

    Importing `tan.planner.orchestrator` needs *some* bound SDK root, because
    `tan/planner/paths.py` evaluates `REPO = sdk_root()` at its own import
    time. Which root it ends up being is inert to every assertion in the three
    consumer modules (see `baremetal_project` and the note at the end of this
    docstring), so all this has to do is bind SOMETHING -- without wrecking
    the process for every other test in the session. That last part is the
    hard part, and it took three rounds on tan-cli#1044:

      * **Round 1 -- never force an unbind.** `monkeypatch.setattr(
        planner_root, "_BOUND", None)` before every test, rebinding a fresh
        `tmp_path` dummy each time, on the theory that `monkeypatch` undoes
        the damage at teardown. It undoes the *variable*, but `paths.py` is
        already in `sys.modules` with `REPO` / `METADATA_ROOT` frozen from
        whatever was bound at ITS import instant; unbinding `_BOUND`
        afterwards cannot un-freeze it. So the first test in the module to
        import `tan.planner` froze `REPO` at a throwaway directory for every
        later test in the session. Measured, with a real alp-sdk checkout
        bound: `pytest tests/planner -q` went `122 passed` -> `14 failed,
        111 passed, 1 skipped` with that module present, and back to
        `122 passed` with it deleted.

      * **Round 2 -- "reuse whatever is already bound" is not enough
        either.** `tests/core` sorts before `tests/planner`, and
        `tests/core/test_flow_d_manifest_fields.py::_bind_stub_sdk_root`
        leaves a NON-SDK stub (its own directory) bound. That fixture is not
        itself the hazard -- it never imports the real `tan.planner` package,
        it loads `loader.py`/`orchestrator.py` standalone under a synthetic
        package name -- but round 2 reused the stub it left behind and
        imported the REAL `tan.planner` under it, freezing `REPO` at the stub
        for the whole process. Every later `bind_sdk_root(<real SDK>)` then
        raised `PlannerRootError`, because `bind_sdk_root` only forbids a
        rebind once `"tan.planner" in sys.modules`, which by then it was.
        Measured: `pytest tests/core/test_flow_d_manifest_fields.py
        tests/planner -q` went `18 passed, 122 errors`; deleting just that
        file restored `136 passed`; the reverse order passed `140 passed` --
        proving the bug is an ORDERING hazard, not an alphabetical accident.

      * **Round 3 -- bind the REAL checkout FIRST**, before anything (a
        consumer of this helper or any other module) can freeze `tan.planner`
        at a stub: when `SDK` is set and `tan.planner` has not been imported
        yet in this process, bind to it unconditionally. `bind_sdk_root`
        permits exactly this rebind -- it only refuses a rebind to a
        DIFFERENT root once `"tan.planner" in sys.modules` -- so it wins over
        a stub bound earlier in the session and is a correct no-op when the
        real root is already bound. Only when `SDK` is unset (the default,
        unbound `gates` job) or `tan.planner` is already imported (nothing
        left to protect by rebinding) does this fall back to reusing whatever
        is bound, or to a throwaway `tmp_path` stub when nothing is.

    In the unbound `gates` job (`SDK is None`) this is no different from any
    other binder in the suite: it reuses what is bound, or falls back to a
    throwaway stub, and it does not itself keep a non-SDK stub from being
    frozen there. Nothing reds there today only because every other binder in
    the suite also skips when there is no real root -- incidental, not
    structural.

    Which of the three roots wins is inert to the consumers' assertions:
    `_slice_post_commands` reads only `slice_.os`; the other two modules pin
    `BoardProject.metadata_root` explicitly (see `baremetal_project`) and
    anchor every asserted path on the test's own `base_dir`, so `_tokenize`
    resolves it against `${PROJECT_ROOT}` and never consults `REPO` at all.
    """
    if SDK is not None and "tan.planner" not in sys.modules:
        planner_root.bind_sdk_root(SDK)
        return
    try:
        planner_root.sdk_root()
    except planner_root.PlannerRootError:
        root = SDK if SDK is not None else tmp_path / "fake-sdk-root"
        root.mkdir(parents=True, exist_ok=True)
        planner_root.bind_sdk_root(root)


@pytest.fixture(autouse=True)
def bound_sdk_root(tmp_path):
    """`bind_planner_sdk_root` as an autouse fixture.

    Imported (not redefined) by each consumer module -- the same
    `import a fixture for its side effect` idiom
    `tests/commands/test_build_streaming.py` uses for `project`. A
    `tests/planner/conftest.py` would be the other way to share it and is
    deliberately NOT used: that would make the binding autouse for every
    module in the directory, including the real-SDK-gated ones that do their
    own binding, which is a behaviour change to tests this work does not
    own.
    """
    bind_planner_sdk_root(tmp_path)


@pytest.fixture
def base_dir(tmp_path) -> Path:
    """The project's own `board.yaml` directory -- what `_slice_command` and
    the baremetal helpers anchor every relative path on (issue #596).

    Resolved, so the `${PROJECT_ROOT}` tokenisation `_tokenize` performs
    against it matches the resolved paths `_resolve_app_path` /
    `_baremetal_output_dir` hand it. Carries a `src/` because that is what a
    baremetal slice's `app: ./src` points at.
    """
    project_dir = (tmp_path / "project").resolve()
    (project_dir / "src").mkdir(parents=True)
    return project_dir


def slice_of(os_: str, *, core_id: str = "m55_he", **kwargs):
    """A bare `Slice` for the control cases -- no project, no build dir.

    Lazy `Slice` import for the module-scope reason in this file's own
    docstring.
    """
    from tan.planner.models import Slice

    return Slice(core_id=core_id, os=os_, **kwargs)


def baremetal_project(
    base_dir: Path,
    *,
    os_: str = "baremetal",
    sku: str = "E1M-AEN801",
    family: str = "aen",
    board_name: Optional[str] = None,
    capabilities: Optional[dict[str, Any]] = None,
    unpopulated: Optional[list[str]] = None,
    core_id: str = "m55_he",
    app: Optional[str] = "./src",
    toolchain: Optional[str] = None,
    build_dir: Optional[str] = "build/m55_he-baremetal",
):
    """A synthetic `(BoardProject, Slice)` that reaches the planner's
    baremetal arms with nothing on disk but `base_dir/src/`.

    `metadata_root` is pinned to `base_dir / "metadata"` -- a directory that
    deliberately does NOT exist. Everything the baremetal arms read out of it
    tolerates that by design and this is checked, not assumed:
    `resolve_capabilities` resolves the SoC JSON through `resolve_soc_path`,
    which returns None for a preset with no `silicon:` at all (so `soc_caps`
    is `{}` and only the `capabilities:` passed here survive), and
    `libraries.baremetal_cmake_args` short-circuits on an empty selection
    before it loads a single manifest. Pinning it matters even so: without
    it, `BoardProject.effective_metadata_root()` falls through to
    `paths.METADATA_ROOT` -- the process-global frozen at import time -- and
    the emitted cache args would depend on WHICH alp-sdk checkout (if any)
    the session happened to bind. That is the pollution hazard
    `bind_planner_sdk_root` documents, arriving by the other door.

    `build_dir` is RELATIVE on purpose: it is the shape a real plan carries,
    and it is what makes `_baremetal_output_dir` /
    `_baremetal_project_include_arg`'s `base_dir` anchoring (issue #596)
    observable at all -- an absolute one would pass whether they anchored on
    `base_dir` or on `Path.cwd()`.
    """
    from tan.planner.models import BoardProject

    som_preset: dict[str, Any] = {"family": family}
    if capabilities is not None:
        som_preset["capabilities"] = capabilities
    if unpopulated is not None:
        som_preset["silicon_capabilities"] = {"unpopulated": unpopulated}
    slice_ = slice_of(
        os_,
        core_id=core_id,
        app=app,
        toolchain=toolchain,
        build_dir=None if build_dir is None else Path(build_dir),
    )
    project = BoardProject(
        sku=sku,
        hw_rev=None,
        board_name=board_name,
        board_hw_rev=None,
        cores={core_id: slice_},
        ipc=[],
        soc_spec={},
        som_preset=som_preset,
        board_preset=None,
        metadata_root=base_dir / "metadata",
    )
    return project, slice_
