#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regenerate `python/release-requirements.lock.txt`, the release input freeze.

tan-cli#437: the release build (`release.yml`'s `build` job and
`clean-host.yml`'s `freeze-and-smoke` job) used to run

    pip install ".[monitor]" "pyinstaller>=6.10"

against a live PyPI resolution, with no lock, no hashes, and an unbounded
`pyinstaller` floor. Re-running the SAME tag on a later day could freeze a
DIFFERENT dependency tree -- a different typer/click/rich/pyyaml/jsonschema/
truststore/certifi/pyinstaller -- and ship different executable bytes under an
identical version string. This script is how the lock that fixes that gets
REGENERATED; `python/release-requirements.lock.txt` is the artefact both
release workflows now install from with `pip install --require-hashes`.

Only third-party distributions go in the lock -- never `alp-tan` itself. The
local package is always installed from the checked-out commit
(`pip install --no-deps -e .` in the workflows), which is already exactly
reproducible (it's the git tree at the tag); locking it too would mean
publishing a hash of our own source tree we'd have to keep in sync by hand.

Universal resolution (`--universal`), not a per-platform lock: `uv` resolves
markers (`sys_platform == 'win32'`, `'darwin'`, ...) into ONE file and
attaches every wheel/sdist hash PyPI has for each pinned version, so the same
file verifies a `pip install --require-hashes` on Windows, both macOS legs,
and the glibc-floor Linux container -- matching the four release targets
`release.yml`'s `build` job actually freezes.

WHAT'S LOCKED: the runtime dependency set (`[project.dependencies]` +the
`monitor` extra`pyserial`, since a frozen binary bundles it -- see
`build_binary.sh`'s header) plus the two BUILD-TIME tools every freeze needs
that pyproject.toml deliberately does not declare as a runtime dependency:
`pyinstaller` (and its own transitive hooks/contrib/platform deps -- pulled in
automatically by resolving it here, not hand-listed) and `setuptools` (pip's
build-isolation floor for `[build-system] requires`, tan-cli#382).

USAGE

    uv pip install --quiet uv   # or: pip install uv
    python python/scripts/generate_release_lock.py           # regenerate
    python python/scripts/generate_release_lock.py --check    # verify only

`--check` fails (exit 1) and prints a diff-shaped message when the committed
lock no longer matches what `pyproject.toml`'s declared dependencies resolve
to today -- e.g. after `dependencies = [...]` gained or lost an entry and
nobody re-ran this script. It does NOT re-pin to newer releases on every run
(`uv pip compile` without `--upgrade` keeps existing pins stable across a
run that adds an unrelated package), so a `--check` failure means the INPUT
changed, not merely that time passed.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve()
PYTHON_DIR = HERE.parents[1]
PYPROJECT = PYTHON_DIR / "pyproject.toml"
LOCK = PYTHON_DIR / "release-requirements.lock.txt"
#: Committed, not generated -- see that file's own header. A tempfile here
#: used to work too, but its randomised name leaked into the lock's own
#: `# via -r <tmpname>.in` provenance comments, which made two back-to-back
#: runs with NO input change produce a spurious diff and made `--check`
#: worthless (a rerun could never match the committed file byte-for-byte).
BUILD_TIME_EXTRAS_IN = HERE.parent / "release-lock-build-time-extras.in"


def _uv() -> str:
    uv = shutil.which("uv")
    if uv is None:
        sys.exit(
            "generate_release_lock.py: `uv` is not on PATH. Install it first "
            "(`pip install uv` or https://docs.astral.sh/uv/) -- this script "
            "shells out to `uv pip compile` rather than hand-rolling a "
            "resolver, so the lock it produces is exactly what a real "
            "resolution run gives."
        )
    return uv


def _compile(output: Path) -> None:
    cmd = [
        _uv(),
        "pip",
        "compile",
        str(PYPROJECT.relative_to(PYTHON_DIR)),
        "--extra",
        "monitor",
        str(BUILD_TIME_EXTRAS_IN.relative_to(PYTHON_DIR)),
        "--universal",
        "--generate-hashes",
        "--python-version",
        "3.12",
        "--no-header",
        "-o",
        str(output),
    ]
    subprocess.run(cmd, cwd=PYTHON_DIR, check=True)

    header = (
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# Generated by `python python/scripts/generate_release_lock.py`.\n"
        "# DO NOT hand-edit -- run the script again and commit its output.\n"
        "# Installed with `pip install --require-hashes -r <this file>` by\n"
        "# release.yml's `build` job and clean-host.yml's `freeze-and-smoke`\n"
        "# job (tan-cli#437). See that script's module docstring for what is\n"
        "# and is not covered.\n"
    )
    output.write_text(header + output.read_text(encoding="utf-8"), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a scratch file and diff against the committed lock; "
        "exit 1 (printing the diff) if they disagree, without touching the "
        "committed file.",
    )
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp) / "release-requirements.lock.txt"
            _compile(scratch)
            old = LOCK.read_text(encoding="utf-8") if LOCK.exists() else ""
            new = scratch.read_text(encoding="utf-8")
            if old == new:
                print(f"OK: {LOCK} matches what pyproject.toml resolves to today.")
                return 0
            import difflib

            diff = "".join(
                difflib.unified_diff(
                    old.splitlines(keepends=True),
                    new.splitlines(keepends=True),
                    fromfile=str(LOCK),
                    tofile="freshly resolved",
                )
            )
            print(
                "STALE: python/release-requirements.lock.txt no longer matches "
                "a fresh resolution of pyproject.toml's declared dependencies. "
                "Run `python python/scripts/generate_release_lock.py` and "
                "commit the result.\n" + diff,
                file=sys.stderr,
            )
            return 1

    _compile(LOCK)
    print(f"wrote {LOCK}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
