complete -c tan -f
complete -c tan -n '__fish_use_subcommand' -a 'validate generate init scaffold examples doctor completion diff presets pinmux explain inspect trace debug-config support-bundle sdk bootstrap build kconfig image flash run clean renode size migrate lock quality model monitor new-som faultdecode'
complete -c tan -l project -d 'Project root'
complete -c tan -l board-yaml -d 'board.yaml path'
complete -c tan -l sdk-root -d 'SDK root path'
complete -c tan -l target -d 'Generation target' -a 'zephyr-conf dts-overlay native-sim-overlay cmake-args yocto-conf carrier-netlist west-libraries zephyr-board hw-info-h'
complete -c tan -l all -d 'Generate all targets'
complete -c tan -l format -d 'Output format' -a 'text json'
complete -c tan -l verbose -d 'Verbose output'
complete -c tan -l quiet -d 'Quiet output'
complete -c tan -l no-color -d 'Disable color output'
complete -c tan -l non-interactive -d 'Disable prompts'
complete -c tan -l ci -d 'CI mode'
complete -c tan -l help -d 'Show help'
complete -c tan -l version -d 'Show version'
complete -c tan -n '__fish_seen_subcommand_from validate' -l offline -d 'Offline structural validation only'
complete -c tan -n '__fish_seen_subcommand_from generate' -l force -d 'Overwrite existing files'
complete -c tan -n '__fish_seen_subcommand_from generate' -l core -d 'Core id (zephyr-board target)'
complete -c tan -n '__fish_seen_subcommand_from explain' -l template -d 'Template id'
complete -c tan -n '__fish_seen_subcommand_from examples' -l filter -d 'Substring match on id/title'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l template -d 'Template id'
complete -c tan -n '__fish_seen_subcommand_from init' -l from-example -d 'Example source dir'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l name -d 'Name value'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l destination -d 'Destination path'
complete -c tan -n '__fish_seen_subcommand_from init' -l som -d 'SoM SKU'
complete -c tan -n '__fish_seen_subcommand_from init' -l cores -d 'Cores list'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l preview -d 'Preview only'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l force -d 'Overwrite existing files'
complete -c tan -n '__fish_seen_subcommand_from pinmux' -l sku -d 'SoM SKU'
complete -c tan -n '__fish_seen_subcommand_from pinmux' -l family -d 'Pinmux family'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l target-kind -d 'Debug target kind' -a 'zephyr-mcu baremetal-mcu yocto-userspace native-host'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l server -d 'Debug server' -a 'jlink openocd pyocd gdbserver none'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l build -d 'Build readiness preflight'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l fix -d 'Auto-repair a fixable blocker'
complete -c tan -n '__fish_seen_subcommand_from inspect trace support-bundle' -l path -d 'Field path'
complete -c tan -n '__fish_seen_subcommand_from inspect' -l show-origin -d 'Include source metadata'
complete -c tan -n '__fish_seen_subcommand_from debug-config' -l target-kind -d 'Debug target kind' -a 'zephyr-mcu baremetal-mcu yocto-userspace native-host'
complete -c tan -n '__fish_seen_subcommand_from debug-config' -l server -d 'Debug server' -a 'jlink openocd pyocd gdbserver none'
complete -c tan -n '__fish_seen_subcommand_from debug-config' -l core -d 'Build slice core id'
complete -c tan -n '__fish_seen_subcommand_from debug-config' -l pre-launch-task -d 'VS Code task to run before launching'
complete -c tan -n '__fish_seen_subcommand_from debug-config' -l preview -d 'Preview only'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l destination -d 'Destination path'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l target-kind -d 'Debug target kind' -a 'zephyr-mcu baremetal-mcu yocto-userspace native-host'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l server -d 'Debug server' -a 'jlink openocd pyocd gdbserver none'
complete -c tan -n '__fish_seen_subcommand_from completion' -l shell -d 'Shell type' -a 'bash zsh fish'
complete -c tan -n '__fish_seen_subcommand_from sdk' -a 'list install current switch'
complete -c tan -n '__fish_seen_subcommand_from sdk' -l destination -d 'Cache root'
complete -c tan -n '__fish_seen_subcommand_from sdk' -l global -d 'Pin the machine-global default'
complete -c tan -n '__fish_seen_subcommand_from bootstrap' -l no-pip -d 'Skip pip install'
complete -c tan -n '__fish_seen_subcommand_from bootstrap' -l no-west -d 'Skip west init/update'
complete -c tan -n '__fish_seen_subcommand_from bootstrap' -l print-env -d 'Print environment lines only'
complete -c tan -n '__fish_seen_subcommand_from bootstrap' -l workspace -d 'Build the workspace at this path'
complete -c tan -n '__fish_seen_subcommand_from build' -l plan -d 'Show the build plan'
complete -c tan -n '__fish_seen_subcommand_from build' -l plan-from -d 'Read build plan from file'
complete -c tan -n '__fish_seen_subcommand_from build' -l materialise -d 'Materialise plan files'
complete -c tan -n '__fish_seen_subcommand_from build' -l native -d 'Build natively'
complete -c tan -n '__fish_seen_subcommand_from build' -l manifest -d 'Show the system manifest'
complete -c tan -n '__fish_seen_subcommand_from build' -l manifest-from -d 'Read manifest from file'
complete -c tan -n '__fish_seen_subcommand_from build' -l no-auto-bootstrap -d 'Never bootstrap implicitly'
complete -c tan -n '__fish_seen_subcommand_from build' -l pristine -d 'Force-wipe build dirs before dispatch'
complete -c tan -n '__fish_seen_subcommand_from kconfig' -l core -d 'Core id to scope the menu to'
complete -c tan -n '__fish_seen_subcommand_from image flash clean renode size' -l build-root -d 'Override build root'
complete -c tan -n '__fish_seen_subcommand_from flash' -l dry-run -d 'Print planned commands only'
complete -c tan -n '__fish_seen_subcommand_from flash' -l core -d 'Flash only this core'
complete -c tan -n '__fish_seen_subcommand_from flash' -l helper -d 'Flash only this helper MCU'
complete -c tan -n '__fish_seen_subcommand_from flash' -l skip-missing-tools -d 'Skip entries with no tool on PATH'
complete -c tan -n '__fish_seen_subcommand_from run' -l flash -d 'Flash the board after building'
complete -c tan -n '__fish_seen_subcommand_from run' -l core -d 'Flash only this core'
complete -c tan -n '__fish_seen_subcommand_from clean' -l dry-run -d 'List targets without removing'
complete -c tan -n '__fish_seen_subcommand_from renode size' -l board -d 'Override SoM SKU'
complete -c tan -n '__fish_seen_subcommand_from renode' -l core -d 'Zephyr slice core id'
complete -c tan -n '__fish_seen_subcommand_from renode' -l image-bundle -d 'Pre-built artefacts dir'
complete -c tan -n '__fish_seen_subcommand_from renode' -l log -d 'Console log file'
complete -c tan -n '__fish_seen_subcommand_from renode' -l timeout -d 'Wall-clock cap in seconds'
complete -c tan -n '__fish_seen_subcommand_from renode' -l expect -d 'Stop early on this substring'
complete -c tan -n '__fish_seen_subcommand_from renode' -l sim-mode -d 'Studio hardware-simulator mode'
complete -c tan -n '__fish_seen_subcommand_from size' -l fail-over-budget -d 'Exit non-zero over budget'
