complete -c tan -f
complete -c tan -n '__fish_use_subcommand' -a 'validate generate explain presets init scaffold diff completion inspect trace doctor support-bundle'
complete -c tan -l project -d 'Project root'
complete -c tan -l board-yaml -d 'board.yaml path'
complete -c tan -l sdk-root -d 'SDK root path'
complete -c tan -l format -d 'Output format' -a 'text json'
complete -c tan -l verbose -d 'Verbose output'
complete -c tan -l quiet -d 'Quiet output'
complete -c tan -l no-color -d 'Disable color output'
complete -c tan -l non-interactive -d 'Disable prompts'
complete -c tan -l ci -d 'CI mode'
complete -c tan -l help -d 'Show help'
complete -c tan -n '__fish_seen_subcommand_from generate' -l target -d 'Generation target' -a 'zephyr-conf dts-overlay native-sim-overlay cmake-args yocto-conf carrier-netlist'
complete -c tan -n '__fish_seen_subcommand_from generate' -l all -d 'Generate all targets'
complete -c tan -n '__fish_seen_subcommand_from explain' -l template -d 'Template id'
complete -c tan -n '__fish_seen_subcommand_from explain' -l target -d 'Generation target'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l template -d 'Template id'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l name -d 'Name value'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l destination -d 'Destination path'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l preview -d 'Preview only'
complete -c tan -n '__fish_seen_subcommand_from init scaffold' -l force -d 'Overwrite existing files'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l target-kind -d 'Debug target kind' -a 'zephyr-mcu baremetal-mcu yocto-userspace native-host'
complete -c tan -n '__fish_seen_subcommand_from doctor' -l server -d 'Debug server' -a 'jlink openocd pyocd gdbserver none'
complete -c tan -n '__fish_seen_subcommand_from inspect trace support-bundle' -l path -d 'Field path'
complete -c tan -n '__fish_seen_subcommand_from inspect' -l show-origin -d 'Include source metadata'
complete -c tan -n '__fish_seen_subcommand_from trace support-bundle' -l target -d 'Generation target' -a 'zephyr-conf dts-overlay cmake-args yocto-conf'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l destination -d 'Destination path'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l target-kind -d 'Debug target kind' -a 'zephyr-mcu baremetal-mcu yocto-userspace native-host'
complete -c tan -n '__fish_seen_subcommand_from support-bundle' -l server -d 'Debug server' -a 'jlink openocd pyocd gdbserver none'
complete -c tan -n '__fish_seen_subcommand_from completion' -l shell -d 'Shell type' -a 'bash zsh fish'