# SPDX-License-Identifier: Apache-2.0
"""Target 2 -- an existing v0.4.1 Rust-`tan` user upgrades to this port with NO
manual migration -- checked against the two distinct on-disk states a real
v0.4.1 project tree is left in.

These states were measured by running the ACTUAL released v0.4.1 binary
(``tan-x86_64-unknown-linux-gnu``, ``tan 0.4.1``), not read out of the Rust
source:

* **materialised only** -- ``tan build --materialise`` writes exactly six
  ``build/`` files and NO ``build/system-manifest.yaml``; the manifest is a
  POST-BUILD artefact.
* **built** -- a real ``tan build`` writes those same six files PLUS
  ``build/system-manifest.yaml``.

This module can only reproduce the first state hermetically: the port has no
standalone ``--materialise``/``--manifest`` mode yet (see ``build_cmd.py``'s
module docstring -- ``tan build`` always both materialises and dispatches), so
what stands in for "materialised only" here is a `--plan-from` run with no
resolvable SDK -- the post-build manifest write then reports "no alp-sdk
checkout resolved" and never reaches disk (`build.manifest-write-failed`,
covered by `write_post_build_manifest`'s own gated tests in
`test_build_manifest.py`), which is byte-for-byte the same on-disk shape a
real `--materialise`-only run leaves. The "built" half -- a real SDK's
`--emit system-manifest` landing on disk with the overlay applied -- is
already covered, hermetically AND against a real SDK checkout, by
`test_build_manifest.py`'s `write_post_build_manifest` suite; this module does
not repeat that coverage.

**What IS new here, and load-bearing for Target 2:**

* The materialised-only tree's LAYOUT RULE and BANNER, checked against the
  real captured plan `tests/parity/oracle/multicore_rpmsg-aen.build-plan.json`
  -- whose six artefact paths are exactly the six the real v0.4.1 binary wrote
  (`build/generated/**` for shared artefacts, `build/<core_id>-<os>/` per
  slice). Deliberately NOT a whole-file byte comparison: this fixture was
  captured from a different point in the SDK's history than the v0.4.1
  session's measurement, and the artefact CONTENTS have already drifted
  (verified: this fixture's `dts-partitions.dtsi` is 299 bytes, matching the
  measured v0.4.1 output byte for byte, but every other file here differs by
  tens to hundreds of bytes) even though the LAYOUT and BANNER are stable.
  That drift is exactly why the banner + layout rule -- not whole-file bytes
  -- is the correct compatibility assertion.
* That the materialised-only tree carries no `system-manifest.yaml`.
* That the real v0.4.1 `.alp/sdk-path` pointer shape --
  `{"sdkPath": ..., "updatedAt": ...}`, not a bare path -- round-trips through
  `tan build`'s own project-pin discovery tier with NEITHER key touched by
  this port, i.e. an unmigrated v0.4.1 pointer file is honoured verbatim.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

#: ``python/`` -- pinned onto the child's PYTHONPATH so ``python -m tan``
#: resolves from a scratch cwd without a ``pip install``.
PACKAGE_ROOT = Path(__file__).resolve().parents[2]

#: Repo root; the captured real plans live under ``tests/parity/oracle/``.
REPO_ROOT = PACKAGE_ROOT.parent
ORACLE_PLANS = REPO_ROOT / "tests" / "parity" / "oracle"

#: Verbatim across every artefact kind the SDK emits (`.h`, `.dtsi`, `.conf`)
#: -- the C-comment and `#`-comment forms both carry this substring.
BANNER = "Auto-generated by scripts/alp_orchestrate.py"

#: The six paths the measured v0.4.1 `--materialise` run wrote, and the same
#: six the real captured `multicore_rpmsg-aen` plan's `sharedArtefacts` +
#: per-slice `configArtefacts` declare -- same example project, same layout
#: rule, a different point in the SDK's history. `(path, slice_name_or_None)`:
#: a per-slice file must name its own slice; a shared one need not name any.
EXPECTED_ARTEFACTS = (
    ("build/generated/alp/system_ipc.h", None),
    ("build/generated/dts-partitions.dtsi", None),
    ("build/generated/dts-reservations.dtsi", None),
    ("build/a32_cluster-yocto/local.conf", "a32_cluster"),
    ("build/m55_he-zephyr/alp.conf", "m55_he"),
    ("build/m55_hp-zephyr/alp.conf", "m55_hp"),
)


def real_plan(name: str) -> dict:
    """Load a captured real build plan by name. A missing fixture RAISES --
    a silently skipped case would let this suite certify nothing."""
    path = ORACLE_PLANS / f"{name}.build-plan.json"
    if not path.is_file():
        raise RuntimeError(
            f"missing oracle plan {path}; this suite is grounded in the real "
            "captured plans and must not fall back to a synthetic one"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def run_tan(*argv, cwd, scrub_path=False):
    """Spawn the port. ``scrub_path`` empties ``PATH`` so no plan tool
    (``west``/``bitbake``) can possibly resolve -- a slice must then take the
    ``executionPolicy.missingTool`` branch instead of launching a real
    multi-minute Zephyr/Yocto build on whichever developer machine runs this."""
    env = {
        **os.environ,
        "PYTHONPATH": os.pathsep.join(
            [str(PACKAGE_ROOT), *([p] if (p := os.environ.get("PYTHONPATH")) else [])]
        ),
    }
    if scrub_path:
        env["PATH"] = ""
    return subprocess.run(
        [sys.executable, "-m", "tan", *argv],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=cwd,
        env=env,
    )


def envelope_of(proc):
    assert proc.stdout.strip(), f"no envelope on stdout; stderr was:\n{proc.stderr}"
    try:
        return json.loads(proc.stdout)
    except ValueError as err:  # noqa: TRY003 -- diagnostic, not control flow
        raise AssertionError(
            f"stdout is not exactly one JSON document ({err})\nstdout:\n{proc.stdout}"
        ) from err


def write_plan(directory: Path, plan: dict) -> Path:
    path = directory / "plan.json"
    path.write_text(json.dumps(plan), encoding="utf-8", newline="")
    return path


@pytest.fixture
def project(tmp_path):
    root = tmp_path / "proj"
    root.mkdir()
    return root


def test_materialise_only_state_has_the_v041_layout_and_banner_and_no_manifest(project):
    plan_doc = real_plan("multicore_rpmsg-aen")
    plan = write_plan(project, plan_doc)
    # No `--sdk-root`/`--board-yaml`: the post-build manifest write cannot
    # resolve an SDK, so this run leaves the tree in exactly the same shape a
    # real v0.4.1 `--materialise`-only run does (see module docstring).
    proc = run_tan(
        "build", "--plan-from", str(plan), "--format", "json", cwd=project, scrub_path=True
    )
    env = envelope_of(proc)
    assert proc.returncode == 0, env

    for rel, slice_name in EXPECTED_ARTEFACTS:
        content = (project / rel).read_text(encoding="utf-8")
        assert BANNER in content, f"{rel} missing the v0.4.1 banner: {content[:120]!r}"
        if slice_name is not None:
            assert slice_name in content, f"{rel} does not name its own slice {slice_name!r}"

    # The layout rule itself: every per-slice file lives under its own
    # `build/<core_id>-<os>/`, every shared one under `build/generated/`.
    for rel, slice_name in EXPECTED_ARTEFACTS:
        if slice_name is None:
            assert rel.startswith("build/generated/"), rel
        else:
            sl = next(s for s in plan_doc["slices"] if s["coreId"] == slice_name)
            assert rel.startswith(f"build/{slice_name}-{sl['backend']}/"), rel

    # The structural finding this whole module exists to pin: materialising
    # is not building, and does not write the manifest.
    assert not (project / "build" / "system-manifest.yaml").exists()


def test_a_full_v041_shaped_sdk_path_pointer_resolves_unmigrated(project, tmp_path):
    # The real shape `tan init`/`tan bootstrap` wrote under v0.4.1: a JSON
    # document with BOTH `sdkPath` and `updatedAt`, never a bare path. This
    # port must read it as-is, with no migration step of its own.
    sdk = tmp_path / "elsewhere-sdk"
    (sdk / "scripts").mkdir(parents=True)
    (sdk / "scripts" / "alp_project.py").write_text("", encoding="utf-8", newline="")

    alp_dir = project / ".alp"
    alp_dir.mkdir()
    (alp_dir / "sdk-path").write_text(
        json.dumps({"sdkPath": str(sdk), "updatedAt": "2026-01-01T00:00:00Z"}),
        encoding="utf-8",
        newline="",
    )

    plan = write_plan(project, real_plan("multicore_rpmsg-aen"))
    proc = run_tan(
        "build",
        "--plan-from",
        str(plan),
        "--board-yaml",
        "board.yaml",
        "--format",
        "json",
        cwd=project,
        scrub_path=True,
    )

    env = envelope_of(proc)
    assert proc.returncode == 0, env
    assert env["sdk"]["root"].replace("\\", "/") == str(sdk).replace("\\", "/")
    assert env["sdk"]["sourceTier"] == "projectPin"
