/*
 * Auto-generated by scripts/alp_orchestrate.py -- do not edit.
 * Regenerate after changes to board.yaml `ipc:` or the SoM's
 * memory_map / mailbox blocks.
 */

#ifndef ALP_SYSTEM_IPC_H
#define ALP_SYSTEM_IPC_H

#define ALP_IPC_SKU "E1M-AEN801"

/* rpmsg channel 'alp_default_rpmsg' -- endpoints a32_cluster, m55_hp */
/* BLOCKED: memory_map.base is TBD for region 'mram_main' in SoM E1M-AEN801; this SoM hasn't been HW-mapped yet so IPC carve-outs cannot be allocated.  Add a `memory_map:` block to metadata/e1m_modules/E1M-AEN801.yaml (or per-region `base`) or remove the matching ipc entry from board.yaml. */
/* IPC channel 'alp_default_rpmsg' is blocked; fix the SoM metadata before depending on this channel at runtime. */
#define ALP_IPC_ALP_DEFAULT_RPMSG_NAME       "alp_default_rpmsg"
#define ALP_IPC_ALP_DEFAULT_RPMSG_ADDR       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_DEFAULT_RPMSG_SIZE       0x0u  /* stub: blocked */
#define ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT    0x0u  /* stub: blocked */
#define ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH    0u    /* stub: blocked */

#endif /* ALP_SYSTEM_IPC_H */
