/*
 * Auto-generated by scripts/alp_orchestrate.py -- do not edit.
 * Regenerate after changes to board.yaml `storage:`.
 */
/* clang-format off */

#include <zephyr/fs/fs.h>
#include <zephyr/storage/flash_map.h>

/* No mountable storage[] entries declared; emitting empty table. */

const struct fs_mount_t *alp_storage_mounts[] = { 0 };
const size_t alp_storage_mount_count = 0;
/* clang-format on */
